In [1]:
# We learn in this course thorugh 
# theory, example and pratice promblems 
# The primary Data Structure in numpy is n-dimension array
# it will be focus of the course.
# Before we dive in numpy array lets motivate their existence 

2.0.1


# why numpy exists 

### in native python store data

In [ ]:
# suppose you have a lot of data of price of stock measured every second
# for a year that's about 32 million values
# for native python you reprsent this information 
# data structure  in list. lets see example

prices = []
N =60*60*60*365
# N = secoonds * minute * hour * year
for i in range(N):
    prices.append(100 + i/100)

print(prices[:5]) # print first five price outputs

### cal avg of prices in native python

In [ ]:
avg = 0.0
for p in prices:
    avg += p/len(prices)

print(avg)


394299.9949999997


### store data in numpy

In [ ]:
# this is slow in native python lets do in numpy 

import numpy as np

prices = 100 + np.array(N)/100
print(prices[:5])


### avg in numpy

In [ ]:
avg = np.mean(prices)
print(avg)

# all the math operations

## concept points

In [ ]:
# the key takeaway are 
# numpy array's are fast that's why they exists
# all the math convient func, random number generator and other things 
# provided by numpy package are secondary benefit to the numpy array data structure
# The speed of the numpy data structure. are primary benefit 

# why numpy array's are faster than list

In [ ]:
# watch animation video of it 

In [ ]:
#   numpy                                      list      
# store homogenous data                      store hetergenous data
# if store directly in byte                 ex [hello i am banana]
#                                            this size is different
#                           solution architer is use pointer 

# it knows how exact to each elemnt       # it do one step extra to fetch
# fetch                                        data from it

In [ ]:
# know the difference between list and array
# array-->  store homegenous type of data 
#Example 
#  a array of int  .   var = [10,20,30]
#  a  array of strings  var = [focus, on ,process, then ,mind]
#  a  array of floats    var = [0.1,0.2,0.3,0.4]
# but not array of int,float together 

In [ ]:
#                       array             list
# Size                  fixed             dyanmic
# memory                takes less        more 

# Store-data            homogenous     heterogenous 
# speed of execution     fast             slow

In [ ]:
# matlab 2 advantage and 2 disadantage in both 
# kuch paya tho kuch ko diya 

# Rules For Every NumPy Array¶
There are two basic rules for every numpy array..

1. Every element in the array must be of the same type and size.
2. If an array's elements are also arrays, those inner arrays must have the same type and number of elements as each other. In other words, multidimensional arrays must be rectangular, not jagged.

## hetergenous array

In [ ]:
# what happen if i create a hetergenous array
import numpy as np
mixed_array = np.array(['hello',2, 3.14, True])
print(mixed_array)
# it convert every data -type to string interally
mixed_array.dtype
# <U32 = unicode characters store's 32 bits only 

['hello' '2' '3.14' 'True']


dtype('<U32')

In [ ]:
# if you store a very large sting compare to 32 bits only
mixed_array[0] = 'a really really really large string '

In [ ]:
print(mixed_array) # it actually truncated the string

['a really really really large str' '2' '3.14' 'True']


## different data type

In [ ]:
# create 2d list one is int other is float
foo = np.array([
    [1,2,3,4],
    [10.1,10.2,10.3,10.4]
])
foo
# it actually casts every element to float
# meaning from two examples hum chota data -type sa bada data-type ma ja 
# sakta ha ya numpy internal kar deta ha 

array([[ 1. ,  2. ,  3. ,  4. ],
       [10.1, 10.2, 10.3, 10.4]])

what happen if you create a jagged array example create different size array

In [ ]:
# outer list list have 4 elements
# inner list have 2 elements

np.array([
    [1,2,3,4],
    [2,3]
])
# ValueError: setting an array element with a sequence.
#  The requested array has an inhomogeneous shape after 1 dimensions.
#  The detected shape was (2,) + inhomogeneous part.

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

# Create array

Create 0D array

In [ ]:
import numpy as np
zero_d = np.array(2)
print(zero_d)

2


In [ ]:
# check dimension or axes
zero_d.ndim

0

### Create 1D array

In [ ]:
import numpy as np
one_d = np.array([1,2,3,4,5])
print(one_d)


[1 2 3 4 5]


how many elements in array 
using size

In [ ]:
len(one_d)

5

In [ ]:
print(one_d.size)


5


Check its dimesnion

In [ ]:
one_d.ndim

1

### Create 2D array

In [ ]:
#list of list (nested list)
two_d = np.array([
    [1,2,3],
    [5,6,7]
])
print(two_d)

[[1 2 3]
 [5 6 7]]


In [ ]:
# if you do
len(two_d)
# its tells you how many nested list persent

2

In [ ]:
two_d.size

6

In [ ]:
two_d.nbytes

24

### create 3D array

In [ ]:
three_d = np.array([[
        [1,2],
        [3,4],
        [5,6]
]])
print(three_d)


[[[1 2]
  [3 4]
  [5 6]]]


In [ ]:
three_d.ndim

3

In [ ]:
three_d[0,0]

array([1, 2])

# methods to create array


### create array of zeros

In [ ]:
#shape how many rows and columns
np.zeros(shape=(3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Create arrays of one

In [ ]:
np.ones(shape= (5,6), dtype = 'int32')

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

### Create array by custom fill

In [ ]:
np.full(shape=(2,3), fill_value='cat')

array([['cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat']], dtype='<U3')

### sequence of arrays


In [ ]:
np.arange(10) # stop

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,7) # start # stop (stop is not included)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.arange(start=1,stop=12,step=3)

array([ 1,  4,  7, 10])

### random number

In [ ]:
np.random.randint(low=1,high=7)
# selected with replacement 

5

In [ ]:
np.random.randint(low=1,high=7,size=(2,3))
#its like rolling two itersions(loops) of three dice

array([[4, 3, 1],
       [4, 6, 3]])

# Indexing 1-d

In [ ]:
foo = np.array([10,20,30,40,50])
print(foo)

[10 20 30 40 50]


Access element 

In [ ]:
foo[0]
# it's like python list 
#np.array([10,20,30,40,50])
#index      0  1  2  3  4
#          -5 -4 -3 -2 -1

10

In [ ]:
# you can also do
foo[len(foo)- 1]  # access last element

50

negative indexing

In [ ]:
# accesing last element
foo[-1]

50

you can access and modify it

In [ ]:
#foo[3]
foo[3] = 99
foo

array([10, 20, 30, 99, 50])

Access multiple elements

In [ ]:
#make a list of elements you want of access
#[0,1,3] items 0, 1 and 3
# foo[]
foo[[0,1,3]]

array([10, 20, 99])

note indexes must not be unique

In [ ]:

print(foo[[0,1,3,0,1]])

[10 20  5 10 20]


## index slicing

extract element what you want

In [ ]:
foo[:2]

array([10, 20])

reverse a array

In [ ]:
foo[::-1]

array([50,  5, 30, 20, 10])

In [ ]:
foo[[0,1,4]]= 2
print(foo)


[ 2  2 30  5  2]


if size not same 

In [ ]:
foo[[2,3,4]] = [91,92]

ValueError: shape mismatch: value array of shape (2,) could not be broadcast to indexing result of shape (3,)

In [ ]:
foo[[2,3,4]] = [91,92,93]
print(foo)

[10 20 91 92 93]


# indexing multidimensional

## Concept

In [ ]:
#[rows_index , column_index]
    # 0  1  2  3
# 0 [ 5 10 15 20]
# 1 [25 30 35 40]
# 2 [45 50 55 60]
# thinking of like coordinates in space

In [ ]:
#bar = np.arange(5,61,5)
for i in range(5,61,5):
    print(i,end=' | ')
#print(bar,end='|')

5 | 10 | 15 | 20 | 25 | 30 | 35 | 40 | 45 | 50 | 55 | 60 | 

In [ ]:
for i in range(0,4):
    print(i,end=' |  ')

0 |  1 |  2 |  3 |  

In [ ]:
# internal numpy store data as contiguous block of data 

# data  =  5 | 10 | 15 | 20 | 25 | 30 | 35 | 40 | 45 | 50 | 55 | 60 | 
#axis 0 = 0  |  0 |  0 |  0 | 1  |  1 |  1 |  1 |  2 |  2 |  2 |  2 | rows
#axis 1 = 0  |  1 |  2 |  3 | 0  |  1 |  2 |  3 |  0 |  1 |  2 |  3 | column

In [ ]:
# now we can access data using [row indices , column indices]

## Access elements

In [3]:
import numpy as np
bar = np.arange(5,61,5).reshape(3,4)
print(bar)

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]


single points or value 

In [4]:
bar[1,2]

35

In [ ]:
bar[0,0]

5

#if you want entire first row as 1-d array

In [5]:
bar[0] 

array([ 5, 10, 15, 20])

now if u want first element in 2d array

In [ ]:

bar[0,None]

array([[ 5, 10, 15, 20]])

extract first column form matrix or numpy 2d array

In [20]:


bar[:,0]  # [row_start : row_stop ,column_start : column_stop]


array([ 5, 25, 45])

In [21]:
bar

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

## Access multiples element 

 give me 1st and 2nd row form the first     
 give in last column first and last second column

In [23]:

# [row_start: row_stop ,  column_start: column_stop]
bar[1:3,[-2,-1]]

array([[35, 40],
       [55, 60]])

change single one values

In [27]:
bar[0,2] = 99
bar

array([[ 0, 10, 99, 20],
       [25,  0, 35, 40],
       [45, 50,  0, 60]])

modify values by assigning them

In [26]:
# convert diganol to 0
bar[[0,1,2],[0,1,2]]= [0,0,0]
print(bar)

[[ 0 10 99 20]
 [25  0 35 40]
 [45 50  0 60]]


# Higher dimension mental model

## 1-d array or 1 dimension

In [28]:
import numpy as np
np.arange(0,51,10)

array([ 0, 10, 20, 30, 40, 50])

## 2-d array or matrix      
think of 1-arrays of rows or column makes it 

In [31]:
'[ 0, 10, 20, 30, 40, 50]'*5
[ 0, 10, 20, 30, 40, 50],
[ 0, 10, 20, 30, 40, 50],
[ 0, 10, 20, 30, 40, 50],
[ 0, 10, 20, 30, 40, 50],
[ 0, 10, 20, 30, 40, 50],

'[ 0, 10, 20, 30, 40, 50],[ 0, 10, 20, 30, 40, 50],[ 0, 10, 20, 30, 40, 50],[ 0, 10, 20, 30, 40, 50],[ 0, 10, 20, 30, 40, 50],'

## 3-d array or 3 dimesion 
think of as rows of matrix or columns of matrix 

In [56]:
a ='''        [ 0, 10, 20, 30, 40, 50]
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        '''
print(a)
def third_dim():
        for i in range(0,3):
                print(a,)


third_dim()

        [ 0, 10, 20, 30, 40, 50]
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        
        [ 0, 10, 20, 30, 40, 50]
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        
        [ 0, 10, 20, 30, 40, 50]
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        
        [ 0, 10, 20, 30, 40, 50]
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        


## 4-da array or 4 dimesion     
think of matrix of matrix

In [57]:
b = third_dim
c = str(b())
print(c)

        [ 0, 10, 20, 30, 40, 50]
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        
        [ 0, 10, 20, 30, 40, 50]
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        
        [ 0, 10, 20, 30, 40, 50]
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        [ 0, 10, 20, 30, 40, 50],
        
None


In [58]:
print(type(c))

<class 'str'>


3d index

In [ ]:
zoo = np.arange(0,12).reshape(2,3,2)
print(zoo)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [ ]:
zoo[0,2,0]

4

In [ ]:
# zoo = np.array([
#     [
#         [10,20],
#         [30,40],
#         [50,60],
#     ],
#     [
#         [11,12],
#         [13,14],
#         [15,16],
#     ]
# ])
# print(zoo)


In [ ]:
zoo.shape

(2, 3, 2)

In [ ]:
array = np.arange(0,45).reshape(3,3,5)
print(array)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]


3-d concept

In [ ]:
# array[matrix_index,rows_index, column_index]
#           0                   1                   2
#       0  1  2  3  4       0  1  2  3  4       0  1  2  3  4   
# 0 [[[ 0  1  2  3  4]     [[15 16 17 18 19]   [30 31 32 33 34]
# 1  [ 5  6  7  8  9]      [20 21 22 23 24]   [35 36 37 38 39]
# 2  [10 11 12 13 14]]     [25 26 27 28 29]]  [40 41 42 43 44]]]

# basic math

 Concept
numpy do math element wise add, sub, mul, div, exp, log

add

In [61]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(6,10).reshape(2,2)
print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]


In [ ]:
arr1 +arr2

array([[ 7,  9],
       [11, 13]])

In [ ]:
arr1 - arr2

array([[-5, -5],
       [-5, -5]])

add scaler to all elements

In [ ]:
arr1 + 5

array([[6, 7],
       [8, 9]])

broadcasting multiplication

In [62]:
arr1*10

array([[10, 20],
       [30, 40]])

matrix multiplication

In [2]:
arr1 * arr2

NameError: name 'arr1' is not defined