In [2]:
import numpy as np
dailywts = (185 - np.arange(5*7)/5).reshape(7,5)
print(dailywts.mean(axis=0))


[182.  181.8 181.6 181.4 181.2]


Make the following 4x7 array called nola that starts with 1 and steps by 2. However, note that the first element in each row is always 4 more than the last element in the previous ro

In [13]:
#Solution
nola = np.arange(start=1,stop=62,step=2)
nola

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61])

In [15]:
nola = np.arange(start=1,stop=62,step=2)
index = [7,14,21]
arr = np.delete(nola, index)
arr.reshape(4,7)

array([[ 1,  3,  5,  7,  9, 11, 13],
       [17, 19, 21, 23, 25, 27, 31],
       [33, 35, 37, 39, 41, 45, 47],
       [49, 51, 53, 55, 57, 59, 61]])

In [140]:
# seed function learn what random number top pause
np.random.seed(5555)
gold = np.random.randint(low = 1,high= 7, size=(7,7))
print(gold)


[[3 5 6 3 3 4 4]
 [1 6 3 1 5 5 4]
 [1 1 6 1 2 6 6]
 [4 4 3 3 1 2 5]
 [3 2 5 6 5 1 5]
 [1 2 2 3 1 5 3]
 [4 5 3 4 4 1 3]]


In [93]:
locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])
print(locs)

[[0 4]
 [2 2]
 [2 3]
 [5 1]
 [6 3]]


In [148]:
def num(x):
    return np.linspace(start=1,stop=10,num=x)
num(1)

array([1.])

In [158]:
num(1)

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [172]:
arr1 = np.arange(0,8).reshape(1,8)
arr2 = np.arange(0,8).reshape(8,1)
print(arr1 + arr2)

[[ 0  1  2  3  4  5  6  7]
 [ 1  2  3  4  5  6  7  8]
 [ 2  3  4  5  6  7  8  9]
 [ 3  4  5  6  7  8  9 10]
 [ 4  5  6  7  8  9 10 11]
 [ 5  6  7  8  9 10 11 12]
 [ 6  7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13 14]]


In [1]:
print('hello')


hello


In [5]:
import numpy as np
a = np.array([1,2,3])
a


array([1, 2, 3])

In [1]:
import pandas as pd
a = pd.Series([2,3,4,5])
a

0    2
1    3
2    4
3    5
dtype: int64

In [5]:
import pandas as pd
number = []
for i in range(10):
    number.append(i)
#print(number)
display(pd.Series(number))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [7]:
import pandas as pd 
import numpy as np

sn = np.arange(1,11)
#print(1/sn)
display(pd.DataFrame(sn),'1/{}'.format(sn))

,0
0,1
1,2
2,3
3,4
4,5
5,6
6,7
7,8
8,9
9,10


'1/[ 1  2  3  4  5  6  7  8  9 10]'

In [15]:
#a = '1/{}'.format(sn)
for n in range(1,11):
    print('1/{}'.format(n))
#print(a)

1/1
1/2
1/3
1/4
1/5
1/6
1/7
1/8
1/9
1/10


In [ ]:
import numpy as np
import pandas as pd
perent = np.array([12,10,8.5,7.6,7.3,6.1,6.4,6.4,7,4.9,5.2,2.4,3.4,2.4,2.7])
ques = perent/100 *40
chapter_name = ['sets&func' ,'number', 'p&c' 'lcd' 'geomatary' 'polynomail' 'compelex'
'aod' 'trigno' 'Sequence and series' 'defeinte intergration area'
'straight line' 'conic' 'arithmetic' 'matric and determinaent']
np.round(ques)
print(pd.Series(data= ques , index=chapter_name))
    

In [26]:
import numpy as np
import pandas as pd
perent = np.array([12,10,8.5,7.6,7.3,6.1,6.4,6.4,7,4.9,5.2,2.4,3.4,2.4,2.7])
ques = np.round(perent/100 *40)
chapter_name = np.array(['sets&func',
'number',
'p&c',
'lcd',
'geomatary',
'polynomail',
'compelex',
'aod',
'trigno',
'Sequence and series',
'defeinte intergration area',
'straight line',
'conic',
'arithmetic',
'matric and determinaent'

                            ])
pd.Series(data= ques,
        index=chapter_name)



sets&func                     5.0
number                        4.0
p&c                           3.0
lcd                           3.0
geomatary                     3.0
polynomail                    2.0
compelex                      3.0
aod                           3.0
trigno                        3.0
Sequence and series           2.0
defeinte intergration area    2.0
straight line                 1.0
conic                         1.0
arithmetic                    1.0
matric and determinaent       1.0
dtype: float64

# Main thing by gorm

In [ ]:
# in some challenges you have what you learned or what you know
# but in some cases the solution require new a new function or trick that
# you don't see 
# now that's the purpose because in the real world you come acrooss aren't the
# limited things you alreday seen  so part of being good data scientist 
# search solution online read documentaion and chatgpt 

 # high school promblem
 With your high school reunion fast approaching, you decide to get in shape and lose some weight . You record your weight every day for five weeks starting on a Monday.

In [2]:
import numpy as np

dailywts = 185 - np.arange(5*7)/5

print(dailywts)

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


Given these daily weights, build an array with your average weight per weekend1.

In [3]:
dailywts.size # or
# tho total 35 days mena apna weight record kiya 
# starting day --> monday
# ending day --> sunday

# 1 weeek = 7 days 
# x week = 35 days 
# 5 weeks
# aor mera mission ha har ek week ma avg weight kasa karga

35

In [12]:
# dailywts array 1d ha uss 1 into 7 matrix bano 
weekly_dailywts = dailywts.reshape(5,7)
print(weekly_dailywts)
# fir har ek row ka avg la lo


[[185.  184.8 184.6 184.4 184.2 184.  183.8]
 [183.6 183.4 183.2 183.  182.8 182.6 182.4]
 [182.2 182.  181.8 181.6 181.4 181.2 181. ]
 [180.8 180.6 180.4 180.2 180.  179.8 179.6]
 [179.4 179.2 179.  178.8 178.6 178.4 178.2]]


array([182.2, 182. , 181.8, 181.6, 181.4, 181.2, 181. ])

In [23]:
avgweight= np.mean(weekly_dailywts,axis=0)
for i in avgweight:
    print("weight on week --> ", i)

weight on week -->  182.2
weight on week -->  182.0
weight on week -->  181.79999999999998
weight on week -->  181.6
weight on week -->  181.4
weight on week -->  181.2
weight on week -->  181.0


# nola promblem
Make the following 4x7 array called nola that starts with 1 and steps by 2. However, note that the first element in each row is always 4 more than the last element in the previous row.

In [ ]:
# nola 
#     [ 1  3  5  7  9 11 13],
#     [17 19 21 23 25 27 29],
#     [33 35 37 39 41 43 45],
#     [49 51 53 55 57 59 61]
    

In [18]:
nola = np.arange(1,62,2)
#nola.size
# 31 values lakin upar matix ma 28 values ha 
# jo values nahi chaya una del kar do
index = [7,14,21]
final = np.delete(nola ,index)
print(final.reshape(4,7))

[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 31]
 [33 35 37 39 41 45 47]
 [49 51 53 55 57 59 61]]


# Goldminer
After binge watching the discovery channel, you ditch your job as a trial lawyer to become a gold miner  . You decide to prospect five locations underneath a 7x7 grid of land. How much gold do you uncover at each location?

In [19]:
import numpy as np
np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))
print(gold)
# how much gold in each location 

[[2 3 0 5 2 0 3]
 [8 8 0 7 1 5 3]
 [0 1 6 2 1 4 5]
 [4 0 8 9 9 8 7]
 [4 2 7 0 7 2 1]
 [9 8 9 2 5 0 8]
 [1 9 8 2 6 4 3]]


In [20]:
# location coordinate of gold ex first 0,4 --> 2
locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])
print(locs)

[[0 4]
 [2 2]
 [2 3]
 [5 1]
 [6 3]]


## notes
- gold states how much gold is under each location in the 7x7 grid of land
- locs states the coordinates of the five locations where you dig

In [24]:
gold[locs]
# wrong 

array([[[2, 3, 0, 5, 2, 0, 3],
        [4, 2, 7, 0, 7, 2, 1]],

       [[0, 1, 6, 2, 1, 4, 5],
        [0, 1, 6, 2, 1, 4, 5]],

       [[0, 1, 6, 2, 1, 4, 5],
        [4, 0, 8, 9, 9, 8, 7]],

       [[9, 8, 9, 2, 5, 0, 8],
        [8, 8, 0, 7, 1, 5, 3]],

       [[1, 9, 8, 2, 6, 4, 3],
        [4, 0, 8, 9, 9, 8, 7]]])

In [26]:
# huma ya chaya 
gold[0,4]
# learn concept of indexing in 2d array

2

In [36]:
all_x_cord = locs[:,0]

In [39]:
locs[:,0]

array([0, 2, 2, 5, 6])

In [37]:
all_y_cord= locs[:,1]

In [40]:
locs[:,1]

array([4, 2, 3, 1, 3])

In [38]:
gold[all_x_cord,all_y_cord]
# mil gya gold location 

array([2, 6, 2, 8, 2])

In [42]:
gold[[0, 2, 2, 5, 6] ,[4, 2, 3, 1, 3]] # it maps all location 
#gold[ rows_indices ,   coulmn_indices ]

array([2, 6, 2, 8, 2])