##  Broadcasting

1. (m,n) +(1,n) = (m,n)
2. (1,n) +(m,n) = (m,n)
3. (1,n) +(1,m) = (m,n)

1. Moving backwards from the last dimension of each array,
2. We check if their dimensions are "compatible". Dimensions are compatible if they are equal or either of them is 1
3. If all of A's dimensions are compatible with B's dimensions, or vice versa, they are compatible arrays

In [1]:
import numpy as np
arr1 = np.arange(0,5).reshape(1,5)
arr2 = np.arange(0,5).reshape(5,1)
print(arr1 + arr2)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [1]:
import numpy as np
arr1 = np.arange(0,9).reshape(3,3)
arr2 = np.arange(10,13).reshape(1,3)
print(arr1 + arr2)

[[10 12 14]
 [13 15 17]
 [16 18 20]]


In [3]:
# tip if don't know reshape use (,-1) in last

In [4]:
np.random.seed(1111)
A = np.random.randint(low = 1, high = 10, size = (3, 1, 4))
B = np.random.randint(low = 1, high = 10, size = (2, 1))

print(A)
print(B)



[[[8 6 2 3]]

 [[5 9 7 5]]

 [[9 7 3 7]]]
[[9]
 [4]]


In [5]:
print(A+B)

[[[17 15 11 12]
  [12 10  6  7]]

 [[14 18 16 14]
  [ 9 13 11  9]]

 [[18 16 12 16]
  [13 11  7 11]]]


In [3]:
import numpy as np
a = np.array([1, 2, 3])
b = 2
result = a * b  # Broadcasting b to match the shape of a
result

array([2, 4, 6])

# New axis

In [6]:
#before
C = np.array([3,11,4,5])
D = np.array([5,8,3])
print(C+D)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
#After
C[:,np.newaxis] - D[np.newaxis,:]


array([[-2, -5,  0],
       [ 6,  3,  8],
       [-1, -4,  1],
       [ 0, -3,  2]])

In [ ]:
f = D[np.newaxis,:]
f.shape

(1, 3)

In [ ]:
e = C[:,np.newaxis]
e.shape

(4, 1)

In [ ]:
print(C.shape)
print(D.shape)

(4,)
(3,)


# tanspose

In [ ]:
tra= np.array([
    [12,13],
    [14,15]
    ])
tra.transpose()
#change rows to columns or you say vice versa

array([[12, 14],
       [13, 15]])

# Reshape

In [ ]:
# directly by np
foo = np.arange(1,9)
np.reshape(foo, newshape=(2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# reshape by mehod
print(foo.reshape(4,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


if you pass in parameter of function.       
then it will not change it globally(for instance).      
changes is not permanent.       

In [ ]:
print(foo)

[1 2 3 4 5 6 7 8]


if you  assign it variable then changes are peramantely in program      
do wisely             
assign when you  want to change it permentally           

In [ ]:

foo.shape = (2,2,2)
print(foo)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Boolean indexing

With boolean indexing, you can subset an array A using another array B of boolean values.

In [3]:
import numpy as np
foo = np.array([
    [3, 9, 7],
    [2, 0, 3],
    [3, 3, 1]
])


In [4]:
#foo ==3
#both are same to do subset
mask = foo ==3
print(mask)

[[ True False False]
 [False False  True]
 [ True  True False]]


In [ ]:
#foo[foo ==3]
print(foo[mask])

[3 3 3 3]


In [ ]:
foo[mask] = 0
print(foo)

[[0 9 7]
 [2 0 0]
 [0 0 1]]


In [ ]:
rows_1_and_3 = np.array([True,False,True])
columns_1_and_2 =  np.array([False,True,True])


In [ ]:
foo[rows_1_and_3,:] #like foo[[0,2],:] object[[row_index,col_index]]

array([[0, 9, 7],
       [0, 0, 1]])

In [ ]:
foo[:,columns_1_and_2 ] #like foo[:,[1,2]]

array([[9, 7],
       [0, 0],
       [0, 1]])

# Logical operators

In [ ]:
b1 = np.array([False, False, True, True])
b2 = np.array([False, True, False, True])

b1 & b2  # [False, False, False,  True], and, intersection
b1 | b2  # [False,  True,  True,  True], or, union
b1 ^ b2  # [False,  True,  True, False], xor
~np.array([False, True]) # array([ True, False]) inverse


In [ ]:
names = np.array(["dennis",'dee','charlie','mac','frank'])
ages = np.array([43,44,43,42,74])
gender = np.array(['male','female','male','male','male'])

In [ ]:
#ques who' at least 44
ages >= 44 #greather than or equal to 

array([False,  True, False, False,  True])

In [ ]:
names[ages >= 44]# who's name of the person
# numpy do correspong element

array(['dee', 'frank'], dtype='<U7')

In [ ]:
# Which males are over 42 ?
#tip use parenthesis to sepecify condition
(ages > 42)  & (gender == 'male')


array([ True, False,  True, False,  True])

In [ ]:
names[(ages > 42)  & (gender == 'male')]

array(['dennis', 'charlie', 'frank'], dtype='<U7')

In [ ]:
#and who's not a male or is younger than 43
~(gender=='male') | (ages > 43 )

array([False,  True, False, False,  True])

In [ ]:
names[~(gender=='male') | (ages > 43 )]

array(['dee', 'frank'], dtype='<U7')

# Nan
You can use NaN to represent missing or invalid values. NaN is a floating point constant that numpy reserves and treats specially.

In [ ]:
bot = np.ones(shape=(3,4))
bot[[0,2],[1,2]] = np.nan
print(bot)
print(np.isnan(bot))

[[ 1. nan  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1. nan  1.]]
[[False  True False False]
 [False False False False]
 [False False  True False]]


Ask question is there a null value 

In [ ]:
bot==np.nan
#observe all are false 
#logic what is empty ==empty
#operation are notdefined

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
#all true
#nothing same beahaviour
# empty means empty 
bot != np.nan

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#this is working
print(np.isnan(bot))

[[False  True False False]
 [False False False False]
 [False False  True False]]


NaN is a special floating point constant, so it can only exist inside an array of floats. If you try inserting NaN into an array of integers, booleans, or strings, you’ll get an error or unexpected behavior.

# Infinity

In [ ]:
np.inf

32

In [ ]:
five_d = np.arange(0,32).reshape(2,2,2,2,2)
print(five_d)

[[[[[ 0  1]
    [ 2  3]]

   [[ 4  5]
    [ 6  7]]]


  [[[ 8  9]
    [10 11]]

   [[12 13]
    [14 15]]]]



 [[[[16 17]
    [18 19]]

   [[20 21]
    [22 23]]]


  [[[24 25]
    [26 27]]

   [[28 29]
    [30 31]]]]]


In [ ]:
num = np.arange(0,24).reshape(3,2,4)
print(num)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


# Random Generator


In [11]:
import numpy as np
np.random.seed(123)
np.random.randint(low=1,high=7,size=3)

array([6, 3, 5])

In [13]:
np.random.seed(2357)
np.random.choice(
    a = np.array([1,2,3,4,5,6]),
    size= 3,
    replace= False,
    p = None
)

array([6, 5, 1])

In [36]:
#we make the probabilty bias
np.random.seed()
np.random.choice(
    a = np.array([1,2,3,4,5,6]),
    size= 3,
    replace= False,
    p =np.array([0.1,0.1,0.1,0.1,0.3,0.3])
)

array([1, 5, 6])

In [55]:
np.random.choice(
    a = np.array(['you','can','use','stings']),
    size = 2
)

array(['use', 'stings'], dtype='<U6')

In [ ]:
#review random generator again