# What is numpy
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a `multidimensional array` object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

agar apna ek function apply kiya aor usma apko result dika then
it is temporya change not permanent change in it 
existing array ma koi change nhi hoga nhi array create hoga

# Create numpy array 

## array

In [16]:
import numpy as np 
zero_dim = np.array(12)
print(zero_dim)
print(zero_dim.ndim)

12
0


### one dimension

In [3]:
import numpy as np 
one_dim = np.array([10,20,30,40])
one_dim # a vector

array([10, 20, 30, 40])

### two dimension

In [4]:
two_dim = np.array([
    [10,20],
    [11,12]
])
print(two_dim)# a matrix
print(two_dim.ndim)  # n dimesions 

[[10 20]
 [11 12]]
2


### three dimension 

In [5]:
three_dim = np.array([[
                        [10,20,30],
                        [1,2,3]
                    ]])
print(three_dim)
print(three_dim.ndim)

[[[10 20 30]
  [ 1  2  3]]]
3


### n dimension

In [ ]:
# number o brackets = number of dimension 
# we can create of any dimension array it could be 25 or 100
# and you create in any dimension data type int,float,string,boolean

### dtype

In [4]:
import numpy as np
np.array([10,20,30,40],dtype=float)

array([10., 20., 30., 40.])

In [5]:
import numpy as np
np.array([10,20,30,40],dtype=complex)

array([10.+0.j, 20.+0.j, 30.+0.j, 40.+0.j])

## arrange

In [ ]:
# it's similar like range function in python 

In [7]:
np.arange(1,11) # first include : last exculded 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1,21,4) # step size = 3

array([ 1,  5,  9, 13, 17])

## reshape 
you can now change the shape of the array/martix

In [10]:
np.arange(1,11).reshape(5,2) # 5 rows 2 column

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
# if you trying to do something
np.arange(1,13).reshape(5,5)
# apka size no of elements ka multiples ma hona chaya 

ValueError: cannot reshape array of size 12 into shape (5,5)

## np.zeros 

In [13]:
np.zeros(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## np.ones

In [15]:
np.ones(shape=(3,2))
# Question what is the usecase of it In neural network(Deep learning)
# when you want intialise the weights you use 

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## random 

In [24]:
random_array = np.random.random(size=(2,4)) # size meaning shape of radnom number
print(random_array)
print(random_array.ndim)

[[0.36851388 0.98966475 0.05717665 0.21510486]
 [0.41588681 0.16605983 0.24803988 0.81087159]]
2


## np.linespace 
full name is linearly space 

In [26]:
np.linspace(-10,10,10)
# you provide three things 
# lower range 10
# upper range 10
# number of item you generate  10
# start = -10 , end = +10 in between 8 number
# in a given range /interval equal distance par number generate
# karta ha 

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

## np.identity 

In [29]:
# it can generate identity matrix you study it 
# or the basis vector of coordinate space
np.identity(n=2) # 2 dimension 

array([[1., 0.],
       [0., 1.]])

In [30]:
np.identity(n= 10) # 10 dimension

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Array attribuites
every numpy_object is the object  of ndarry class
 which have certain attributies that you  can access 

In [32]:
array1 = np.array([1,2,3,4,5])
array2 = np.arange(12,dtype=float).reshape(3,4)
array3 = np.arange(8).reshape(2,2,2)

### ndim
number of dimension 

In [34]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)
# given array ka dimension bata ha ki vo 1d,2d ya nd ha

1
2
3


### shape
ki ahar dimension ma kitna element 
ha basically tell you rows and columns 

In [37]:
print(array1.shape)
print(array2.shape)


(5,)
(3, 4)
(2, 2, 2)


In [38]:
print(array3.shape)
print(array3) # 2d array ha aor uska andr 2 rows and 2 columns ha
# rows of matrix ya coloumns of matrix 

(2, 2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### size 
number of elements in the array 

In [40]:
print(array1.size)
print(array2.size)
print(array3.size)
# if you multily all shape element you get size 

5
12
8


### itemsize
memory ma kitna size occpy kar raha ha 

In [43]:
print(array1.itemsize) # 8 bytes 
print(array2.itemsize)
print(array3.itemsize)
# returns the size of each elements in bytes 

8
8
8


In [42]:
print(type(array1.itemsize))

<class 'int'>


In [53]:
array_var = np.array([1,2,3],dtype = 'int64')
print(array_var.itemsize)

8


In [54]:
array_var = np.array([1,2,3],dtype = 'int16')
print(array_var.itemsize)

2


In [67]:
print(np.array([1,2,3],dtype = 'float16').itemsize)
print(np.array([1,2,3],dtype = 'float32').itemsize)
print(np.array([1,2,3],dtype = 'float64').itemsize)
print(np.array([1,2,3],dtype = 'float').itemsize)

2
4
8
8


### dtype
it tells you data type in the array 

In [69]:
print(array1.dtype)
print(array2.dtype)
print(array3.dtype)

int64
float64
int64


# change datatype 

In [3]:
import numpy as np
var = np.array([11,12,13,14])
print(var.dtype)
# example var array store age of the people
# then default it is int64 it takes more memory
# I know ki age ek chota integer ha vo jada value nhi laga

int64


In [4]:
# so I converted in int16 
var.astype(np.int16)
# you do a lot in Data Analysis jab aap data loga aor dekoga
# ki ya sahi coulmn sahi format ma nahi ha  

array([11, 12, 13, 14], dtype=int16)

In [ ]:
# example when you work in big data file example 10 gb
# waha age ki value ko float ma diya bala vo jada memory la ga
# then aap usa int ma convert kar doga
# aab 10gb ka data sayad 9 ma aa jaya 
# do it when you are confident in data type 

# Array Operation 

## Scaler Operation
a scaler and a numpy array 

In [2]:
# just like you learn in operation in python all are
# work in numpy that's the power of python 
# learn one time use many times 
# it can perform operation element wise 
import numpy as np 
arr1 = np.arange(1,5).reshape(2,2)
print(arr1)

[[1 2]
 [3 4]]


### arithmetic

#### add

In [3]:
# moving on number line 
# foward (+)  backward (-)
arr1 + 5

array([[6, 7],
       [8, 9]])

#### sub

In [4]:
arr1 - 5

array([[-4, -3],
       [-2, -1]])

#### mul

In [5]:
# strech (*) and squence (/)
arr1 *5

array([[ 5, 10],
       [15, 20]])

In [6]:
arr1 * 1/5

array([[0.2, 0.4],
       [0.6, 0.8]])

#### modulus

In [7]:
arr1 % 5

array([[1, 2],
       [3, 4]], dtype=int32)

#### interger divison 

In [8]:
arr1 //2

array([[0, 1],
       [1, 2]], dtype=int32)

#### power 

In [9]:
arr1**2

array([[ 1,  4],
       [ 9, 16]])

### relational

#### equal to 

In [11]:
# kiya har ek element  3 ka equal ha 
arr1 == 3

array([[False, False],
       [ True, False]])

#### not equal to 

In [12]:
arr1 != 1

array([[False,  True],
       [ True,  True]])

#### greator than

In [13]:
arr1 > 2

array([[False, False],
       [ True,  True]])

#### less than

In [ ]:
arr1 

## Vector Operation
between two numpy arrays 

### arithmetic 

#### add

In [17]:
# shape should be same while do operation 
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

#### sub 

In [18]:
arr1 - arr2

array([[-4, -4],
       [-4, -4]])

#### mul 

In [19]:
arr1 *arr2

array([[ 5, 12],
       [21, 32]])

#### div

In [20]:
arr1 / arr2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

#### pow

In [21]:
arr1 ** arr2

array([[    1,    64],
       [ 2187, 65536]])

### Relational 

#### equal to 

In [22]:
arr1 == arr2

array([[False, False],
       [False, False]])

#### not equal to 

In [23]:
arr1 != arr2

array([[ True,  True],
       [ True,  True]])

#### greator than 

In [24]:
arr1 > arr2

array([[False, False],
       [False, False]])

#### lessar than

In [26]:
arr1.__lt__(arr2)

array([[ True,  True],
       [ True,  True]])

# Array functions 
har mathamtical operation ka liya apka pass function hoga
that's great actually apko kabhi apna code likna ki jarrut nhi ha apko hamesa bana banya function mil jata ha 

In [29]:
array_var = np.arange(1,10).reshape(3,3)
print(array_var)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### max/min/sum/product

In [34]:
# pura array ma sa maximum number 
np.max(array_var)

9

In [32]:
# 0 means column 
# har column ma max number 
np.max(array_var,axis=0)

array([3, 6, 9])

In [ ]:
# 1 means rows 
# har  rows ma max number 
np.max(array_var,axis=1)

array([3, 6, 9])

In [35]:
np.min(array_var)

1

In [36]:
# total sum of array each element 
# you can also do by row wise or column wise 
np.sum(array_var)

45

In [37]:
# total product of array each element 
np.prod(array_var)

362880

### mean/median/std/var

In [38]:
# by default it is arithmetic mean 
np.mean(array_var)

5.0

In [39]:
np.median(array_var,axis=0)

array([4., 5., 6.])

In [40]:
# calculate standard deviation 
np.std(array_var)

2.581988897471611

In [41]:
# varience 
np.var(array_var)

6.666666666666667

### trignometric function 

In [42]:
np.sin(array_var)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [43]:
np.cos(array_var)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

### dot product

In [47]:
# dot product ka liya phala ka column dursa ka row sa match karna chaya

v1 = np.arange(1,13).reshape(3,4)
v2 = np.arange(12,24).reshape(4,3)
# print(v1)
# print(v2)
np.dot(v1,v2)

array([[180, 190, 200],
       [444, 470, 496],
       [708, 750, 792]])

### log and exponent 

In [48]:
np.log(array_var)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [50]:
np.exp(array_var)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### round/floor/ceil

In [56]:
random_var = np.random.random(size=(3,4))* 100
# i want only interger only 
np.round(random_var)

array([[39.,  2., 50., 23.],
       [75., 10., 70.,  9.],
       [10.,  2., 33., 95.]])

In [57]:
# greatest integer picha la jata 
np.floor(random_var)

array([[38.,  2., 50., 23.],
       [74.,  9., 69.,  9.],
       [ 9.,  2., 33., 94.]])

In [58]:
np.ceil(random_var)

array([[39.,  3., 51., 24.],
       [75., 10., 70., 10.],
       [10.,  3., 34., 95.]])

# Indexing and slicing 
How to access elements in array 

indexing = ek bari ma ek element nikal sakta ho 
slicing = ek bari ma multiple item nikal sakta ho 

In [ ]:
# you do it in basic.ipynb see it 

# iterating 
ap cho tho numpy array par loop chala sakta ho 

### one dim

In [6]:
import numpy as np
one_dim
for i in one_dim:
    print(i)

10
20
30
40


### two dim

In [8]:
two_dim
for i in two_dim:
    print(i)
# we get each row 

[10 20]
[11 12]


### three_dim 

In [10]:
three_dim
for i in three_dim:
    print(i)
# we get every 2d matrix 

[[10 20 30]
 [ 1  2  3]]


### nditer 

In [11]:
# nditer n dimesnion iter 
# kisi bhi n dimension array to 1 dimensation ma la ata ha 
for i in np.nditer(three_dim):
    print(i)

10
20
30
1
2
3


# Reshaping 

### Reshape 

In [ ]:
### we study it change no of element = multiple matix dimesnion
# example 12 element in matrix then 
# (12,1) 12 rows 1 column (1,12) 1 row 12 column
# (6,2 ) 6 rows 2 column  (2,6) 2 rows 6 column
# (3,4)  3 row 4 column   (4,3) 4 row 3 column

In [26]:
array_object = np.arange(0,12).reshape(3,4)

array_object

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Transpose

In [28]:
# both syntax are valid 
np.transpose(array_object)
array_object.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### ravel 

In [31]:
# kitna bhi dimension ka array ko 1 dimension array ma convert
# kar deta ha 
# 4 dimension arra 
four_dim  = np.arange(0,16).reshape(2,2,2,2)
four_dim
np.ravel(four_dim)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# Stacking 

In [ ]:
# stacking and splitting aap dono case ma array ma changes kar raha ho 
# aap 2 ya 2 sa jada numpy array ko jod sakta ho
# 2 tarika ha 
# ya tho aap horizontal jodo side wise  left and right 
# ya tho app vertical jodo  uppar nicha side down 

In [ ]:
# example we have two numpy array 
# [  2 by 2  ]  [ 2 by 2 ]
# you two stack by horizontal and vertical 
# horizontal   [ 2 by 4      ] rows same column increase 

# vertical   [ 4 by 2] rows increase    column same 



### horizontal 

In [5]:
import numpy as np 
array_1 = np.arange(0,4).reshape(2,2)
array_2 = np.arange(4,8).reshape(2,2)
# print(array_1)
# print(array_2)
#np.hstack(  (pass in tuple )  )
np.hstack( (array_1,array_2))

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

### vertical 

In [6]:
np.vstack( (array_1,array_2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

## used when 

In [ ]:
# sometimes happen ki apka multiple data source hoga
# thoda data  api sa aa rha ha 
# thoda data  databse  sa aa rha ha 
# thoda apna web scrapping kiya
# 3 data ha tho similar hi aab apko 3 ko milaga ka analysis karni ha
# you do horizontal or vertical depending on situation
# multiple sources ko jodna ka tarika ha 
# ek hi requirement ha same hona chaya 

# splilting 

## horizontal

In [13]:
matrix = np.arange(0,8).reshape(2,4)
matrix

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
#Split an array into multiple sub-arrays horizontally (column-wise).
np.hsplit(matrix,2)

[array([[0, 1],
        [4, 5]]),
 array([[2, 3],
        [6, 7]])]

## vertical 

In [16]:
matrix = np.arange(0,8).reshape(2,4)
matrix

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
#Split an array into multiple sub-arrays vertically (row-wise).
np.vsplit(matrix,2)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]])]