## Import libraties 

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

## Import dataset

In [2]:
data = pd.read_csv('heart.csv')
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1


In [3]:
X = data.drop(columns='target')
y = data['target']

In [4]:
print(X.shape)
print(y.shape)

(1025, 13)
(1025,)


## train test split 

In [5]:

X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size=0.2,
                                                    random_state=2
                                                    )

## fit model 

In [6]:
logistic_regresion_model = LogisticRegression()
logistic_regresion_model.fit(X_train,y_train)

c:\Users\sumit\miniconda3\envs\my_env\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [7]:
decesion_tree_model = DecisionTreeClassifier()
decesion_tree_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [8]:
# now do predicaction on each model 
y_pred1 = logistic_regresion_model.predict(X_test)
y_pred2 = decesion_tree_model.predict(X_test)

In [9]:
pd.DataFrame(data={
    'actual_label': y_test,
    'Logistic Regression Predication' : y_pred1,
    'Decesion Tree Predication' : y_pred2,
})

,actual_label,Logistic Regression Predication,Decesion Tree Predication
546,0,0,0
980,1,1,1
908,0,0,0
577,0,0,0
846,1,1,1
...,...,...,...
922,1,1,1
832,1,1,1
451,1,1,1
775,1,1,1


# Accuray
$\text{Accuracy} = \frac{\text{Number of correct Predication}}{\text{Total Number of Predications}}$


In [10]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.8536585365853658
Accuracy of Decision Trees 0.9804878048780488


So Decesion Tree perform better

# Confusion matrix 

## binary class

In [11]:
# Logistic Regression
confusion_matrix(y_test,y_pred1)

array([[82, 23],
       [ 7, 93]], dtype=int64)

## multi class

In [12]:
import seaborn as sns
df = sns.load_dataset('iris')
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [14]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['species'] = encoder.fit_transform(df['species'])

In [15]:
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=1)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [17]:
logistic_regresion_model = LogisticRegression()
logistic_regresion_model.fit(X_train,y_train)

LogisticRegression()

In [18]:
decesion_tree_model = DecisionTreeClassifier()
decesion_tree_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [19]:
# now do predicaction on each model 
y_pred1 = logistic_regresion_model.predict(X_test)
y_pred2 = decesion_tree_model.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9666666666666667
Accuracy of Decision Trees 0.9666666666666667


In [20]:
confusion_matrix(y_test,y_pred1)

array([[11,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  6]], dtype=int64)

In [22]:

print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,3)))

Logistic Regression Confusion Matrix



,0,1,2
0,11,0,0
1,0,12,1
2,0,0,6


In [25]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2))

Decision Tree Confusion Matrix



,0,1,2
0,11,0,0
1,0,12,1
2,0,0,6


In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.datasets import load_breast_cancer

In [15]:
X = load_breast_cancer(as_frame=True)['data']
y = load_breast_cancer(as_frame=True)['target']

In [16]:
X

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,radius error,texture error,perimeter error,area error,smoothness error,compactness error,concavity error,concave points error,symmetry error,fractal dimension error,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,1.1760,1.2560,7.673,158.70,0.010300,0.02891,0.05198,0.02454,0.01114,0.004239,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,0.7655,2.4630,5.203,99.04,0.005769,0.02423,0.03950,0.01678,0.01898,0.002498,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,0.4564,1.0750,3.425,48.55,0.005903,0.03731,0.04730,0.01557,0.01318,0.003892,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,0.7260,1.5950,5.772,86.22,0.006522,0.06158,0.07117,0.01664,0.02324,0.006185,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


In [17]:
y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: target, Length: 569, dtype: int32

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,
                                                test_size=0.2,
                                                random_state=2
                                                )

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier


In [21]:
logistic_regresion_model = LogisticRegression()
decesion_tree_model= DecisionTreeClassifier()

In [22]:
logistic_regresion_model.fit(X_train,y_train)
decesion_tree_model.fit(X_train,y_train)

c:\Users\sumit\miniconda3\envs\my_env\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [23]:
y_pred1 = logistic_regresion_model.predict(X_test)
y_pred2 = decesion_tree_model.predict(X_test)

In [24]:

from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9210526315789473
Accuracy of Decision Trees 0.9298245614035088


In [27]:
print('logistic_regresion_model confusion matrix\n')
pd.DataFrame(confusion_matrix(y_test,y_pred1))

logistic_regresion_model confusion matrix



,0,1
0,41,4
1,5,64


In [30]:
print('decesion_tree_model confusion matrix\n')
pd.DataFrame(confusion_matrix(y_test,y_pred2))

decesion_tree_model confusion matrix



,0,1
0,44,1
1,7,62


In [31]:

result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [34]:
result.sample(10)

,Actual Label,Logistic Regression Prediction,Decision Tree Prediction
490,1,1,1
365,0,0,0
383,1,1,1
55,1,1,1
246,1,1,1
152,1,1,1
467,1,1,1
157,1,0,0
486,1,1,0
265,0,0,0


# Precesion score

# Recall score

# F1 Score

In [35]:
from sklearn.metrics import recall_score,precision_score,f1_score

print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  41   4
1   5  64
--------------------------------------------------
Precision -  0.9411764705882353
Recall -  0.927536231884058
F1 score -  0.9343065693430657


In [36]:
print("For Decesion Tree Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For Decesion Tree Model
--------------------------------------------------
    0   1
0  44   1
1   7  62
--------------------------------------------------
Precision -  0.9841269841269841
Recall -  0.8985507246376812
F1 score -  0.9393939393939394


In [39]:
precision_score(y_test,y_pred2,average=None)

array([0.8627451 , 0.98412698])

Class 0 ka score = 0.86              
Class 1 ka score = 0.98

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits

In [4]:
X = load_digits(as_frame = True)['data']
y = load_digits(as_frame = True)['target']

In [5]:
X

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_6,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,0.0,0.0,4.0,10.0,13.0,6.0,0.0,0.0,0.0,1.0,...,4.0,0.0,0.0,0.0,2.0,14.0,15.0,9.0,0.0,0.0
1793,0.0,0.0,6.0,16.0,13.0,11.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,6.0,16.0,14.0,6.0,0.0,0.0
1794,0.0,0.0,1.0,11.0,15.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,9.0,13.0,6.0,0.0,0.0
1795,0.0,0.0,2.0,10.0,7.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,5.0,12.0,16.0,12.0,0.0,0.0


In [6]:
y

0       0
1       1
2       2
3       3
4       4
       ..
1792    9
1793    0
1794    8
1795    9
1796    8
Name: target, Length: 1797, dtype: int32

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,
                                                test_size=0.2,
                                                random_state=2)

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [10]:
logistic_regresion_model = LogisticRegression()
decesion_tree_model = DecisionTreeClassifier()

In [11]:
logistic_regresion_model.fit(X_train,y_train)
decesion_tree_model.fit(X_train,y_train)

c:\Users\sumit\miniconda3\envs\my_env\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [12]:
y_pred1 = logistic_regresion_model.predict(X_test)
y_pred2 = decesion_tree_model.predict(X_test)

In [13]:

from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9444444444444444
Accuracy of Decision Trees 0.8333333333333334


In [ ]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1))

,0,1,2,3,4,5,6,7,8,9
0,31,0,0,0,1,0,0,0,0,0
1,0,41,0,1,0,0,0,0,1,1
2,0,0,31,0,0,0,0,0,0,0
3,0,0,0,33,0,0,0,1,2,0
4,0,0,0,0,31,0,0,0,3,1
5,0,1,0,0,1,41,0,0,0,0
6,0,1,0,0,0,0,33,0,1,0
7,0,0,0,0,0,0,0,39,0,1
8,0,0,0,0,0,0,0,0,35,1
9,0,0,0,1,0,1,0,0,1,25


In [17]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2))

Decision Tree Confusion Matrix



,0,1,2,3,4,5,6,7,8,9
0,30,0,0,0,0,0,0,0,1,1
1,0,34,2,1,0,0,2,0,4,1
2,0,1,29,1,0,0,0,0,0,0
3,0,0,0,24,0,2,0,1,3,6
4,2,0,0,0,26,0,0,4,1,2
5,0,1,0,4,1,37,0,0,0,0
6,1,0,1,0,1,0,31,0,1,0
7,0,0,1,0,2,0,0,35,1,1
8,0,3,0,0,0,1,0,0,31,1
9,0,0,0,1,0,1,0,2,1,23


In [20]:
from sklearn.metrics import precision_score, recall_score,f1_score

In [27]:
# every class precesion
precision_score(y_test,y_pred1,average=None)

array([1.        , 0.95348837, 1.        , 0.94285714, 0.93939394,
       0.97619048, 1.        , 0.975     , 0.81395349, 0.86206897])

In [28]:
# yadi single value chaya  tho 
precision_score(y_test,y_pred1,average='macro')

0.9462952384423916

In [ ]:
# yadi apko weighted precision calucate karna ha tho 
precision_score(y_test,y_pred1,average='weighted')

0.9477543902383517

In [23]:
recall_score(y_test,y_pred1,average='weighted')

0.9444444444444444

In [24]:

f1_score(y_test,y_pred1,average='weighted')

0.9451471115572613

In [25]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       1.00      0.97      0.98        32
           1       0.95      0.93      0.94        44
           2       1.00      1.00      1.00        31
           3       0.94      0.92      0.93        36
           4       0.94      0.89      0.91        35
           5       0.98      0.95      0.96        43
           6       1.00      0.94      0.97        35
           7       0.97      0.97      0.97        40
           8       0.81      0.97      0.89        36
           9       0.86      0.89      0.88        28

    accuracy                           0.94       360
   macro avg       0.95      0.94      0.94       360
weighted avg       0.95      0.94      0.95       360

