In [3]:
# so today we study the useful numpy functions that you may be
# used in your Data Science Journey.


# np.sort

In [4]:
import numpy as np 
array = np.random.randint(1,100,15)
array

array([92, 84, 81, 22, 73, 44, 61, 48, 78, 55,  9, 18, 94,  2, 28])

In [5]:
np.sort(array) # default sort ascending hota ha 

array([ 2,  9, 18, 22, 28, 44, 48, 55, 61, 73, 78, 81, 84, 92, 94])

In [6]:
# for descending ka liya
np.sort(array)[::-1]

array([94, 92, 84, 81, 78, 73, 61, 55, 48, 44, 28, 22, 18,  9,  2])

In [7]:
matrix = np.random.randint(1,100,24).reshape(6,4)
matrix

array([[41,  8, 30, 74],
       [59, 56, 50, 32],
       [80,  8, 80, 72],
       [78, 98, 27, 21],
       [42, 39, 89, 52],
       [65, 45, 57, 44]])

In [8]:
np.sort(matrix,axis = 1) # row wise sort

array([[ 8, 30, 41, 74],
       [32, 50, 56, 59],
       [ 8, 72, 80, 80],
       [21, 27, 78, 98],
       [39, 42, 52, 89],
       [44, 45, 57, 65]])

In [9]:
np.sort(matrix,axis = 0) # column wise sort

array([[41,  8, 27, 21],
       [42,  8, 30, 32],
       [59, 39, 50, 44],
       [65, 45, 57, 52],
       [78, 56, 80, 72],
       [80, 98, 89, 74]])

# np.append

In [10]:
array = np.array([1,2,3,4,5])
np.append(array,200) # append 200 at the end of the array

array([  1,   2,   3,   4,   5, 200])

In [11]:
matrix

array([[41,  8, 30, 74],
       [59, 56, 50, 32],
       [80,  8, 80, 72],
       [78, 98, 27, 21],
       [42, 39, 89, 52],
       [65, 45, 57, 44]])

In [12]:
np.append(matrix,[[1,2,3,4]],axis = 0) # append row wise

array([[41,  8, 30, 74],
       [59, 56, 50, 32],
       [80,  8, 80, 72],
       [78, 98, 27, 21],
       [42, 39, 89, 52],
       [65, 45, 57, 44],
       [ 1,  2,  3,  4]])

In [13]:
np.append(matrix,np.ones(shape=(6,1)),axis = 1) # append column wise

array([[41.,  8., 30., 74.,  1.],
       [59., 56., 50., 32.,  1.],
       [80.,  8., 80., 72.,  1.],
       [78., 98., 27., 21.,  1.],
       [42., 39., 89., 52.,  1.],
       [65., 45., 57., 44.,  1.]])

# np.concenate

In [14]:
array_1 = np.arange(6).reshape(2,3)
array_2 = np.arange(6,12).reshape(2,3)
print(array_1)
print(array_2)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [15]:
np.concatenate((array_1,array_2),axis = 0) # row wise concatenate

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
np.concatenate((array_1,array_2),axis = 1) # column wise concatenate

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique

In [17]:
an_array = np.array([1,1,2,2,3,3,4,4,5,5,6,6,6])
np.unique(an_array) # ya unique values dega apko dataset ma sa
# example ek website ma multipe courses aor users unma enrol karta ha 
# muja jan na ha ki kitna unique student na courses ma enrol kiya ha 

array([1, 2, 3, 4, 5, 6])

In [18]:
# check repeated values in a dataset and frequency count of it.
np.unique(an_array,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([2, 2, 2, 2, 2, 3], dtype=int64))

# np.expand_dims

In [19]:
# aap expand kar sakta ho kisi bhi dimesnion ma
# 1d ko 2d and 2d ko 3d bana ka liya
# aap es sa row vector and coloumn vector bana sakta ha

array

array([1, 2, 3, 4, 5])

In [20]:
array.shape

(5,)

In [21]:
np.expand_dims(array,axis=0) # row wise expand dimension
# row vector.

array([[1, 2, 3, 4, 5]])

In [22]:
np.expand_dims(array,axis=0).shape

(1, 5)

In [23]:
np.expand_dims(array,axis=1) # coloumn wise expansion dim

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [24]:
np.expand_dims(array,axis=1).shape # coloumn vector

(5, 1)

In [25]:
# usecase in machine learning and deep learning is 
# In ML
# [ iq marks]
# ML algo bolta ha muja ek student nahi batches of student do

# In DL
# IN CNN muja ek image nahi balki batches of images do 

In [26]:
# in numpy indices row = 0 and coloumn = 1
# but in pandas its reverse coloumn = 0 and row =1 

# np.where
substitution  of conidtion(if -else) decesion making when decide b/w two or many different situation  

### find all indices with value greator than 50 

In [27]:
import numpy as np 
array = np.random.randint(1,100,15)
array

array([59,  2, 26, 76, 86, 27, 38, 83, 73,  9, 60, 92,  8, 86, 19])

In [28]:
np.where(array>50) # you can fetch the index position where condition is true


(array([ 0,  3,  4,  7,  8, 10, 11, 13], dtype=int64),)

In [29]:
#np.where(condition,True,False)

In [30]:
## replace all values > 50 with 0 

In [31]:
#np.where(condition,True,False)
# i am saying conidtion array ma 50 sa bada number ka indices do
# yahi 50 ha tho una 0 kar do 
# aor false wali siutation ma array ko same rehan do no operation perform on it 
np.where(array>50,0,array)
# 

array([ 0,  2, 26,  0,  0, 27, 38,  0,  0,  9,  0,  0,  8,  0, 19])

find even numbers and replace them with 0 

In [32]:
np.where(array%2==0,0,array)

array([59,  0,  0,  0,  0, 27,  0, 83, 73,  9,  0,  0,  0,  0, 19])

# np.argmax
sabsa bada number konsa index position par ha 

In [33]:
array

array([59,  2, 26, 76, 86, 27, 38, 83, 73,  9, 60, 92,  8, 86, 19])

In [34]:
np.argmax(array)


11

In [35]:
array[np.argmax(array)]

92

In [36]:
matrix

array([[41,  8, 30, 74],
       [59, 56, 50, 32],
       [80,  8, 80, 72],
       [78, 98, 27, 21],
       [42, 39, 89, 52],
       [65, 45, 57, 44]])

In [37]:
np.argmax(matrix,axis = 0) # ab ya coloumn wise kyu bata raha ha 

array([2, 3, 4, 0], dtype=int64)

# np.argmin

In [38]:
np.argmin(array)

1

# cumsum 

In [39]:
array

array([59,  2, 26, 76, 86, 27, 38, 83, 73,  9, 60, 92,  8, 86, 19])

In [40]:
np.cumsum(array)

array([ 59,  61,  87, 163, 249, 276, 314, 397, 470, 479, 539, 631, 639,
       725, 744])

In [ ]:
np.cumsum(matrix) # ara isna 2d array ko 1 1d kar diya  

array([  41,   49,   79,  153,  212,  268,  318,  350,  430,  438,  518,
        590,  668,  766,  793,  814,  856,  895,  984, 1036, 1101, 1146,
       1203, 1247])

In [46]:
matrix

array([[41,  8, 30, 74],
       [59, 56, 50, 32],
       [80,  8, 80, 72],
       [78, 98, 27, 21],
       [42, 39, 89, 52],
       [65, 45, 57, 44]])

In [ ]:
np.cumsum(matrix,axis=0) # coloumn wise

array([[ 41,   8,  30,  74],
       [100,  64,  80, 106],
       [180,  72, 160, 178],
       [258, 170, 187, 199],
       [300, 209, 276, 251],
       [365, 254, 333, 295]])

In [ ]:
np.cumsum(matrix,axis=1) # row wise 

array([[ 41,  49,  79, 153],
       [ 59, 115, 165, 197],
       [ 80,  88, 168, 240],
       [ 78, 176, 203, 224],
       [ 42,  81, 170, 222],
       [ 65, 110, 167, 211]])

# np.cumprod

In [48]:
array

array([59,  2, 26, 76, 86, 27, 38, 83, 73,  9, 60, 92,  8, 86, 19])

In [49]:
np.cumprod(array)

array([         59,         118,        3068,      233168,    20052448,
         541416096,  -901024832, -1770617024,  -406023872,   640752448,
        -209558784, -2099538944,   383557632, -1373782016,  -332054528])

# np.percentile

In [ ]:
np.percentile(array,100)
# 100th percentile chaya

92.0

In [51]:
np.percentile(array,0)

2.0

In [ ]:
np.percentile(array,50) # 50th percentile is median 

59.0

In [53]:
np.median(array)

59.0

# np.histogram
frequency count bata ha huma 

In [56]:
array

array([59,  2, 26, 76, 86, 27, 38, 83, 73,  9, 60, 92,  8, 86, 19])

In [55]:
np.histogram(array,bins = [0,10,20,30,40,50,60,70,80,90,100])

(array([3, 1, 2, 1, 0, 1, 1, 2, 3, 1], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [57]:
np.histogram(array,bins = [0,50,100])

(array([7, 8], dtype=int64), array([  0,  50, 100]))

# np.corrcoef

In [ ]:
# correlation coefficient nikalan ka liya 
# 1 +ve  = both inc or dec one direction
# 0  = no relation 
# -1  -ve = one inc or another vari dec  
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

|            | salary | experience
| -----------|--------|-----------
| salary     |  1     |   0.25
| experience | 0.25   |     1

In [ ]:
# salary ka salary ka sath coefficient correlation 1 hoga
# ek Quanity ka apna sath correlation tho 1 hi hoga
# salary ka experinece ka sath 0.25 correlation ha 

# np.isin

In [59]:
# given array ma multiple item search karka bata ha ki 
# vo item array ma ha ki nahi .
array

array([59,  2, 26, 76, 86, 27, 38, 83, 73,  9, 60, 92,  8, 86, 19])

In [60]:
items = [50,60,70,80,90]
np.isin(array,items)

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False])

In [ ]:
# agar apka output dika yani temparay ha
# agar output nahi deka matlab permanent changes ho gaya.


# np.flip
useful jab hum linear transformation kara . 


In [70]:
array

array([59,  2, 26, 76, 86, 27, 38, 83, 73,  9, 60, 92,  8, 86, 19])

In [71]:
np.flip(array)

array([19, 86,  8, 92, 60,  9, 73, 83, 38, 27, 86, 76, 26,  2, 59])

In [72]:
## in 2d
np.flip(matrix)

array([[44, 57, 45, 65],
       [52, 89, 39, 42],
       [21, 27, 98, 78],
       [72, 80,  8, 80],
       [32, 50, 56, 59],
       [74, 30,  8, 41]])

# np.put 
specfic ya  element ko add karna array permanetaly 

In [76]:
our_array = np.array([0,1,2,3,4,5])
our_array

array([0, 1, 2, 3, 4, 5])

In [78]:
np.put(our_array,[0,1],[110,530])
our_array

array([110, 530,   2,   3,   4,   5])

# np.delete

In [79]:
np.delete(our_array,[0,2,4])

array([530,   3,   5])

# set function
you can apply all set function but it give you array instead of set 
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

## np.union1d

In [61]:
array_1 = np.array([1,2,3,4,5])
array_2 = np.array([3,4,5,6,7])
np.union1d(array_1,array_2)

array([1, 2, 3, 4, 5, 6, 7])

## np.intersect1d


In [62]:
np.intersect1d(array_1,array_2)

array([3, 4, 5])

## np.setdiff1d


In [ ]:
# items A ma ha B ma nhi ha 
np.setdiff1d(array_1,array_2)

array([1, 2])

In [ ]:
# items B ma ha A ma nhi ha
np.setdiff1d(array_2,array_1)

array([6, 7])


## np.setxor1d


In [64]:
np.setxor1d(array_1,array_2)

array([1, 2, 6, 7])

## np.in1d

In [ ]:
# given array ma vo element ha ki nhi
# memborship operator

np.in1d(array_1,array_2)

array([False, False,  True,  True,  True])

# np.clip

In [67]:
array

array([59,  2, 26, 76, 86, 27, 38, 83, 73,  9, 60, 92,  8, 86, 19])

In [ ]:
# given range ma value rakna 
# example abhi hum  25 sa 75 range ma rakna ha 

In [69]:
np.clip(
    a = array,
    a_min=25,
    a_max=75,
    )

array([59, 25, 26, 75, 75, 27, 38, 75, 73, 25, 60, 75, 25, 75, 25])