**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [9]:
import numpy as np
all_zeros = np.zeros(shape=(10))
all_zeros[4]=1 # assign 5th index element to 1
all_zeros

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [10]:
null_vector = np.full(shape=(10),fill_value=0)
null_vector[4]= 1

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [12]:
import numpy as np
# take first and second number input 
a = int(input('enter the first num '))
b = int(input('enter the first num '))

# call the random func and pass the variable a and b
random_array = np.random.random(size=(a,b))
print('the random array  is :',random_array)
# use the average func 
print('the avg is :',np.mean(random_array))

the random array  is : [[0.12184336 0.19735139 0.24983665]
 [0.85330958 0.74375336 0.94309166]]
the avg is : 0.5181976656118824


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [24]:
# create array of ones using function 
# then use array of zeros inside it use and operator 
# 4*4 array of 1 than iska andr 2*2 array of 0 insert kar do 
# but Question is he can not perform operation on it 
# or you can thing of which logical operation of perform between
# array of 1 and 0 so I got this ouput 
ones = np.ones(shape=(4,4),dtype=np.int64)
# use indexing to change it value to 0 then generalise it 
# use slicing 
ones[1:3,1:3] = 0
print(ones)
# make a function take a (n,n) convert to ((n - (n-1)) -(n-1)))
# this is a genralise equation lets do it 

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [26]:
def pattern(a,b ):
    ones = np.ones(shape=(a,b),dtype=np.int8)
    # now how can you write slicing 
    ones[1:3,1:3] = 0
    print(ones)
pattern(4,4)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [8]:
import numpy as np
# random --> Uniformly distributed floats over ``[0, 1)``
vector = np.random.random(size=10)
print(vector)

[0.57511248 0.14910888 0.21468541 0.51539034 0.14890174 0.09751014
 0.97589235 0.01039424 0.85679879 0.73788861]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
# dignal element are 1 everything is 0 
def identity_matrix(a,b):
    zeros = np.zeros(shape=(a,b),dtype=np.int8)
    # assign 0,0  1,1  2,2 3,3 to value 1 # fency indexing concept 
    zeros[[0,1,2,3],[0,1,2,3]] = 1
    print(zeros)

identity_matrix(4,4)


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
# or use the direction function 
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [16]:
np.random.randint(low=0,high=4,size=(5,5))

array([[0, 0, 1, 2, 0],
       [1, 1, 3, 0, 2],
       [1, 1, 3, 2, 3],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 2, 2]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [7]:
import numpy as np 
coordinates = np.random.randint(low=0,high=100,size=(10,2))
print(coordinates)
# find distance using distance formuala from the coordiantes
point = np.array([2,3])
distance = point - coordinates
print("-- Distance of point vector as array --- ")
print(np.sqrt(np.sum(distance**2,axis=1)).astype(int))
# row wise sum kiya axis = 1 sa 

[[69 30]
 [59 67]
 [65 71]
 [18 20]
 [37 71]
 [30 85]
 [12 52]
 [ 2 77]
 [ 7 63]
 [17 43]]
-- Distance of point vector as array --- 
[72 85 92 23 76 86 50 74 60 42]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [27]:
# so find elements in it
#6*7*8 = 336
three_dim = np.arange(0,336).reshape(6,7,8)
# question is how can you find the 100th element index 
three_dim == 100
three_dim[three_dim == 100]

array([100])

In [12]:
an_array = np.zeros(shape=(6,7,8))
print(an_array)
print(np.unravel_index(100,an_array.shape))

[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [22]:
numbers = '1 2 3 4 -8 -10'
def print_array(given_str):
    # split the string on the basis of space 
    #print(given_str.split(' '))
    # extract each element and convert into int 
    number_list = []
    for i in given_str.split(' '):
        number_list.append(int(i))
    #print(number_list)
    # convert into numpy array 
    #print(np.array(number_list))c
    # change the dtype = np.float64
    # reverse the string 
    print(np.array(number_list,dtype=np.float64)[::-1])
print_array(numbers)

[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [23]:
array_var = np.array([1,2,3,4,5])
counter = 0
for i in array_var:
    counter +=1
print('element count: ',counter)

element count:  5


In [ ]:
# or you can use the size function  
np.size(array_var)

5

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [43]:
class OneDimensionError(Exception):
    def message(self):
        print('please enter only one dimension array not higher dimension')

    
def softmax_function(given_array: np.ndarray) -> np.ndarray:
    array_var = np.array(given_array)
    if array_var.ndim == 1:
        expression =  np.exp(array_var)/np.sum(np.exp(array_var))
        print(expression)
    else:
        raise OneDimensionError

input_array = np.array([86.03331084 ,37.7285648  ,48.64908087 ,87.16563062, 38.40852563, 37.20006318])
softmax_function(input_array)

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


In [44]:
two_dim = np.array([
    [1,2],
    [3,4],
])
softmax_function(two_dim)

please enter only one dimension array not higher dimension


OneDimensionError: 

In [26]:
def softmax_function(given_array: np.ndarray) -> np.ndarray:
    array_var = np.array(given_array)
    if type(given_array) != np.ndarray:
        raise TypeError('please enter numpy array')
    elif given_array.ndim > 1:
        raise TypeError('Requires 1D array')
    expression =  np.exp(array_var)/np.sum(np.exp(array_var))
    print(expression)
    
#softmax_function([86.03331084 ,37.7285648  ,48.64908087 ,87.16563062, 38.40852563, 37.20006318])
softmax_function(np.array([86.03331084 ,37.7285648  ,48.64908087 ,87.16563062, 38.40852563, 37.20006318]))

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [27]:
# so multiple input array ma input karu
# aor vo unka vstack kar de use *args concept
def vertical_stack(*args):
    return np.vstack(args)

In [28]:
# a= [[0 1 2 3 4]
#  [5 6 7 8 9]]

# b= [[1 1 1 1 1]
#  [1 1 1 1 1]]
a = np.array([
    [0 ,1, 2, 3, 4],
    [5 ,6 ,7 ,8 ,9]
    ])
b = np.array([
    [1 ,1 ,1, 1, 1],
    [1, 1, 1, 1 ,1]
])
# procide array in tuple 
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
vertical_stack(a,b)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
# a= [[0 1 2 3 4]
#  [5 6 7 8 9]]

# b= [[1 1 1 1 1]
#  [1 1 1 1 1]]

# c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
#  [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]

a = np.array([
    [0 ,1, 2, 3, 4],
    [5, 6 ,7, 8 ,9]
])
b = np.array([
    [1 ,1, 1 ,1, 1],
    [1 ,1 ,1, 1, 1]
])
a_plus_b = np.vstack( (a,b) )
print(a_plus_b)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [31]:
c= np.array([
    [0.10117373 ,0.1677244 , 0.73764059 ,0.83166097, 0.48985695],
    [0.44581567 ,0.13502419 ,0.55692335 ,0.16479622 ,0.61193593]
])
np.vstack( (a_plus_b,c))

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.10117373, 0.1677244 , 0.73764059, 0.83166097, 0.48985695],
       [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

In [32]:
vertical_stack(a,b,c)

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.10117373, 0.1677244 , 0.73764059, 0.83166097, 0.48985695],
       [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [2]:
# so apka pass ek string hai date format ma usko apka split karna hoga
# lakin last element string format ha tho uska int ma convert karna hoga 
# fir uska last element ko extract karno hoga fir loop chalena hoga
#date_array(start = '2020-09-15', end = '2020-09-25')
def date_array(start,end):
    # split the string on the basis of -
    print(start.split('-'))
    print(end.split('-'))
    # convert into int data type
    start_date = [int(i) for i in start.split('-')]
    end_date = [int(i) for i in end.split('-')]
    print(start_date)
    
    run_loop = np.arange(start_date[-1],end_date[-1]+1)
    # now use the concept of string formatting in the dates you can use f string
    # and list compreshion wala loop 
    date_list = [] 
    for i in run_loop:
        date_list.append(f'{start_date[0]}-{start_date[1]}-{i}')
    # convert dates into numpy array
    print(np.array(date_list))

date_array(start = '2020-09-15', end = '2020-09-25')

['2020', '09', '15']
['2020', '09', '25']
[2020, 9, 15]
['2020-9-15' '2020-9-16' '2020-9-17' '2020-9-18' '2020-9-19' '2020-9-20'
 '2020-9-21' '2020-9-22' '2020-9-23' '2020-9-24' '2020-9-25']


In [3]:
date_array(start = '2022-12-01', end = '2022-12-06')

['2022', '12', '01']
['2022', '12', '06']
[2022, 12, 1]
['2022-12-1' '2022-12-2' '2022-12-3' '2022-12-4' '2022-12-5' '2022-12-6']


In [ ]:
def date_array(start,end):
    # split the string on the basis of -
    # convert into intger  data type
    start_date = [int(i) for i in start.split('-')]
    end_date = [int(i) for i in end.split('-')]
    
    run_loop = np.arange(start_date[-1],end_date[-1]+1)
    # now use the concept of string formatting in the dates you can use f string
    # and list compreshion wala loop 
    date_list = [] 
    for i in run_loop:
        date_list.append(f'{start_date[0]}-{start_date[1]}-{i}')
    # convert dates into numpy array
    print(np.array(date_list))

date_array(start = '2020-09-15', end = '2020-09-25')

['2020-9-15' '2020-9-16' '2020-9-17' '2020-9-18' '2020-9-19' '2020-9-20'
 '2020-9-21' '2020-9-22' '2020-9-23' '2020-9-24' '2020-9-25']


In [1]:
import numpy as np 
def date_array(start: str, end:str):
    if type(start) != str or type(end) != str:
        raise TypeError('please enter string')
    
    return np.arange(start,end, dtype='datetime64[D]')
date_array('2020-09-15','2020-09-25')

array(['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
       '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
       '2020-09-23', '2020-09-24'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [9]:
import numpy as np
a_matrix = np.arange(0,16).reshape(4,4)
print(a_matrix)
row_mean = np.mean(a_matrix,axis=1)
print(row_mean)
print(a_matrix - row_mean[:,np.newaxis])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 1.5  5.5  9.5 13.5]
[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]


In [11]:
row_matrix = np.vsplit(a_matrix,4)
row_matrix

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [9]:

result = np.mean(a_matrix)- row_matrix
print(result)

[[[ 7.5  6.5  5.5  4.5]]

 [[ 3.5  2.5  1.5  0.5]]

 [[-0.5 -1.5 -2.5 -3.5]]

 [[-4.5 -5.5 -6.5 -7.5]]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [12]:
two_dim_array  = np.arange(0,8).reshape(4,2)
#print(matrix)
# now swap using assigning 
def swap_column(matrix :np.ndarray)  -> np.ndarray:
    print(matrix)
    # use vstack and split 
    a,b = np.hsplit(matrix,2)
    print(np.hstack((b,a)))
swap_column(two_dim_array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[1 0]
 [3 2]
 [5 4]
 [7 6]]


###`Q-16:` Replace odd elements in arrays with -1.

In [14]:
# use the boolean indexing concept 
# even number divisible by 2 odd not 
def odd_array(given_array: np.ndarray) -> np.ndarray:
    print(given_array)
    # jo 2 sa divisible nahi hoga vo odd hoga
    # now assign it to -1 and print original array
    given_array[given_array % 2 != 0] = -1
    return given_array

odd_array(np.array([1,2,3,4,5,6,7,8,9,10]))

[ 1  2  3  4  5  6  7  8  9 10]


array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [15]:
odd_array(np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[-1,  2, -1,  4],
       [-1,  6, -1,  8],
       [-1, 10, -1, 12]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [8]:
# take two array using do element wise comparison who is max then print 
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
# I am asking is a greator than b element wise 
comparison_1 = a > b
comparison_2 = b > a
print(comparison_1)
print(comparison_2)
result = np.logical_or(comparison_1,comparison_2)
print(a[result])

[ True  True False False  True]
[False False False  True False]
[6 3 5 8]


In [ ]:
# take two array using do element wise comparison who is max then print 
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
a[b>a] = b[a<b]
a
# Question is how can you do element wise comparison
# so I am using the concept of boolean indexing



array([6, 3, 1, 7, 8])

In [18]:
first_array =np.array([6,3,1,5,8])
second_array =np.array([3,2,1,7,2])
# use the boolean indexing concept 
print(first_array>second_array)
first_array[first_array>second_array]

[ True  True False False  True]


array([6, 3, 8])

In [20]:
second_array>first_array
second_array[second_array>first_array]

array([7])

In [27]:
first_array[second_array>first_array] = second_array[first_array<second_array]
first_array

array([3, 2, 1, 7, 2])

In [ ]:
# use boolean indexing concept 
a[a>b]

array([6, 3, 8])

In [6]:
b[b > a]

array([7])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [51]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[7382, 2923, 9285, 4540, 8842],
       [7268, 5922, 7893, 5497, 9410],
       [7168, 6460, 3010, 8695, 4085],
       [5915, 1888, 5716,  615,  208],
       [4394, 4765, 3705, 1219, 1189],
       [8909, 8689, 6268, 1853, 1165],
       [2036, 7090,  907, 9045, 4610],
       [3447, 6854, 4334, 8663, 6142]])

In [54]:
# answer 1 fetech every alternate column array
# all rows 
arr1[:,::2] # step every column 

array([[7382, 9285, 8842],
       [7268, 7893, 9410],
       [7168, 3010, 4085],
       [5915, 5716,  208],
       [4394, 3705, 1189],
       [8909, 6268, 1165],
       [2036,  907, 4610],
       [3447, 4334, 6142]])

In [52]:
normalised = (arr1 - np.min(arr1)) /(np.max(arr1)- np.min(arr1))
print(normalised)

[[0.77961313 0.29504456 0.986416   0.47076722 0.93827429]
 [0.76722452 0.62095197 0.83514453 0.57476636 1.        ]
 [0.75635731 0.67941752 0.30449902 0.9222995  0.42132145]
 [0.62019126 0.18256901 0.59856553 0.04422952 0.        ]
 [0.45490111 0.49521843 0.38002608 0.10986742 0.10660726]
 [0.94555531 0.92164747 0.65855249 0.17876549 0.10399913]
 [0.19865247 0.7478809  0.07596175 0.96033471 0.47837427]
 [0.3519887  0.7222343  0.44838079 0.918822   0.64485981]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [60]:
# take two arugements 1d  numpy array and int -> uski length uska barabar ya kam honi chaya
# jis number par maximum aya vo extract (iska solution sort karo aor indexing nikalao)
def find_max(numpy_array:np.ndarray ,n:int) -> int:
    if  n<=len(numpy_array):
        sorted_array = np.sort(numpy_array)[::-1]
        print(sorted_array[n-1]) # it start from 0 and n is length so we do n-1 for index 
    else: 
        print('please enter number in the array range ')
find_max(numpy_array=(12,34,40,7,1,0),n= 3)

12


In [61]:
find_max(numpy_array=(12,34,40,7,1,0) , n=1)

40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [74]:
# so take a number 
# do it 3 times the number 
simple_array = np.array([1,2,3])
def pattern(numpy_array:np.ndarray) -> np.ndarray:
    
    for i in numpy_array:
        print(i)
    repeat_3_times = np.hstack(  (numpy_array,numpy_array,numpy_array) )
    #print(repeat_3_times)

pattern(simple_array)

1
2
3


In [ ]:
array = np.array([1,2,3])
np.repeat(array,3)
# repeat 3 times

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
np.tile(array,3)
# repeat the array 3 times

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [33]:
np.hstack((np.repeat(array,3),np.tile(array,3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])