###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [12]:
import numpy as np
np.random.seed(1235)
random_array = np.random.randint(low=1,high=100 ,size = 12).reshape(3,4)
random_array

array([[76, 35,  3, 68],
       [72, 36, 55, 17],
       [17, 51, 67, 80]])

In [13]:
# Question 1 
np.sort(random_array)# default sort last axis yani 1 hota yani rows wise

array([[ 3, 35, 68, 76],
       [17, 36, 55, 72],
       [17, 51, 67, 80]])

In [14]:
# Question 1
np.sort(random_array,axis=0) # coloumn wise 

array([[17, 35,  3, 17],
       [72, 36, 55, 68],
       [76, 51, 67, 80]])

In [ ]:
# question 2 
# second column find the index using argsort 
random_array[:,1].argsort()
# usma dalo # now sort by second column 
random_array[random_array[:,1].argsort()]

array([[76, 35,  3, 68],
       [72, 36, 55, 17],
       [17, 51, 67, 80]])

In [22]:
# Question 3 
# their is not any function in numpy we use python func
np.array(sorted(random_array,key=lambda x:max(x)))


array([[72, 36, 55, 17],
       [76, 35,  3, 68],
       [17, 51, 67, 80]])

In [24]:
# Question 4
# when axis = none it first flat the array than sorted ascending order 
np.sort(random_array,axis=None).reshape(3,4)

array([[ 3, 17, 17, 35],
       [36, 51, 55, 67],
       [68, 72, 76, 80]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

i. Add marks every student of an extra subject in the same array.
    

In [ ]:
# subject y axis coloumn axis = 0
# marks  x axis rows axis = 1

In [65]:
marks = np.array([
        [13, 10,  9, 33],
        [63, 46, 90, 42],
        [39, 76, 13, 29],
        [82,  9, 29, 78],
        [67, 61, 59, 36]
        ])
extra_subject = np.array([41, 87, 72, 36, 92])
extra_subject = np.expand_dims(extra_subject,axis=1)
print(extra_subject) # we shape the array 

marks = np.concatenate((marks,extra_subject),axis=1)
marks

[[41]
 [87]
 [72]
 [36]
 [92]]


array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

ii. Add two new students marks in respective 5 subjects.(one subject added in above task)


In [66]:
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1,-1)
rec1

array([[77, 83, 98, 95, 89]])

In [69]:
# make the correct shape of rec1 and rec2
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1,-1)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1,-1)
marks = np.concatenate((marks,rec1,rec2),axis=0) # add the record 

In [70]:
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [ ]:
# sum of each student subject(left to right )
sum_of_std= np.sum(marks,axis= 1,keepdims = True )
sum_of_std

array([[106],
       [328],
       [229],
       [234],
       [315],
       [442],
       [329]])

In [78]:
marks = np.concatenate((marks,sum_of_std),axis=1) # add the sum of each student subject

In [79]:
marks

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

iii. Add extra column with sum of all subjects(5-subjects) marks


iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

In [83]:
np.array(sorted(marks,key=lambda x:x[-1],reverse=True)) # sort by sum of each student subject

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329],
       [ 63,  46,  90,  42,  87, 328],
       [ 67,  61,  59,  36,  92, 315],
       [ 82,   9,  29,  78,  36, 234],
       [ 39,  76,  13,  29,  72, 229],
       [ 13,  10,   9,  33,  41, 106]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [ ]:
arr = np.array([
                [1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]
                ])

np.unique(arr,axis=0) # column wise

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [ ]:
np.unique(arr,axis=1) # row wise 

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [40]:
np.flip(arr)

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

In [42]:
np.flip(arr,axis=1)

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [8, 8, 8, 3, 2, 1],
       [1, 1, 3, 3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [52]:
my_arr = np.array([
        [1,2,3,4,5],
        [10,-3,30,4,5],
        [3,2,5,-4,5],
        [9,7,3,6,5]
        ])
#np.where(condition,true,false)

my_arr[np.where(my_arr>6,)]

array([10, 30,  9,  7])

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [54]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
np.concatenate((arr1,arr2,arr3),axis=0)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [91]:
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
# find max and min indices using argmax and argmin 
print(arr)
max_element = arr.argmax()
min_element = arr.argmin()
print(arr.max(),arr.min())
arr = np.delete(arr,max_element,axis=1)
arr = np.delete(arr,min_element,axis=1)

print(arr.max(),arr.min())

[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]
998 103
997 117


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [62]:
np.clip(
    a= arr,
    a_min=100,
    a_max=200
    )

array([[200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 181, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 137, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 103, 200, 200, 200, 200, 200, 173, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 171, 200, 178, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 117, 200, 200, 123,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 191, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 136, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 193, 200, 200, 200, 200, 200

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [103]:
array = np.random.uniform(1,100,30)
array = np.round(array,3) # round the array to 3 decimal places
print("0th perncntile minimimu value of arry :",np.percentile(array,0))
print("100th perncntile minimimu value of arry :",np.percentile(array,100))
print('difference b/w 51 and 50 perceniile :',np.percentile(array,51)-np.percentile(array,50))

0th perncntile minimimu value of arry : 1.027
100th perncntile minimimu value of arry : 96.888
difference b/w 51 and 50 perceniile : 0.5773900000000012


In [104]:
np.array([1,2,3],dtype='complex')

array([1.+0.j, 2.+0.j, 3.+0.j])

In [106]:
import numpy as np

a = np.array([1, 2, 3, 4, 5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [107]:
np.dtype('i4')

dtype('int32')

In [109]:
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)],dtype=dt)
print(dt)

[('age', 'i1')]


In [111]:
a = np.array([7,10,3,4,13,16])
med = np.percentile(a,50)
print(med)

8.5


In [113]:
array= np.arange(0,132).reshape(11,12)
np.argwhere(array==100)

array([[8, 4]], dtype=int64)

In [118]:
arr = np.array( [
    [1,2,3,4,5], 
    [6,7,8,9,10]
    ] )
arr[1,1]

7