# Apply linear Regression

In [1]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import numpy as np

## load dataset

In [3]:
X,y = load_diabetes(return_X_y=True)

In [4]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


## train test split

In [5]:
X_train, X_test ,y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [6]:
#  check the shape of training and testing data
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(353, 10)
(353,)
(89, 10)
(89,)


## Apply OLS
linear regression on our diabetices dataset

In [8]:
reg_model = LinearRegression()
reg_model.fit(X_train,y_train)

LinearRegression()

## find parameters value

In [9]:
# find parameter value after fitting model
print('intercept :',reg_model.intercept_)
print('coefficents :', reg_model.coef_)

intercept : 151.88331005254167
coefficents : [  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]


## r2 score

In [10]:
# caluate predication and r2 score
y_pred = reg_model.predict(X_test)
print('r2_score :',r2_score(y_test,y_pred))

r2_score : 0.439933866156897


# Mini-batch class

We use our old batch gradient descant class

In [ ]:
class GradientDescantRegressor:

    def __init__(self,learning_rate=0.001,epoches = 100):
        self.intercept_ = None
        self.coef_ = None
        self.learning_rate = learning_rate
        self.epoches = epoches
        
    def fit(self,X_train,y_train):
        # intialise the coeffs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epoches):
            # update all the coeff and the intercept
            y_hat = np.dot(X_train,self.coef_) + self.intercept_
            slope_of_intercept  = -2 * np.mean(y_train - y_hat)
            self.intercept_ = self.intercept_- (self.learning_rate * slope_of_intercept) 

            slope_of_coefficents  =  -2 * np.dot((y_train - y_hat),X_train)/X_train.shape[0]
            self.coef_ = self.coef_ - (self.learning_rate * slope_of_coefficents )
        print('intercept :',self.intercept_)
        print('coefficents :',self.coef_)
        
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_



## fit function change

we create a parameter called batch size

example hamra pass total rows = 100 ha uska batch = group of rows  liya 100 ka  tho batch size 10 hoga yani 10 updates per epoch

$\text{batch size} = \frac{\text{total rows}}{\text{batch group}}$

batch size decide karna ka baad randomly kuch rows choose karo
example hamra batch = 10 tho 10 rows randomly select karo.

In [ ]:
X_train.shape[0]+ 1
# last element is not inclued 

354

In [ ]:
np.random.randint(low=0,high=10+1,size=5)
# lakin yadi last ma one plus karo then inculeded 

array([ 1,  2, 10,  3,  1])

In [ ]:
np.random.randint(low=0,high=X_train.shape[0]+ 1,size=10)

array([ 69,  96, 142,  65,  89, 208, 346, 210, 308,  45])

In [50]:
# now check it how it use it 
random_rows = np.random.randint(low=0,high=X_train.shape[0]+ 1,size=10)
X_train[random_rows] # we use fency indexing numpy concept
# humna un randow rows ko as a index   
X_train[random_rows].shape

(10, 10)

In [54]:
y_hat = np.dot(X_train[random_rows],np.ones(shape=10)) 
y_hat.shape

(10,)

In [55]:
np.random.seed(123)

In [91]:
import random

class MiniBatchGradientDescantRegressor:

    def __init__(self,batch_size,learning_rate=0.001,epoches = 100):
        self.intercept_ = None
        self.coef_ = None
        self.learning_rate = learning_rate
        self.epoches = epoches
        self.batch_size = batch_size
        
    def fit(self,X_train,y_train):
        # intialise the coeffs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epoches):
            for j in range(int(X_train.shape[0]/self.batch_size)):
            # update all the coeff and the intercept
                random_rows_index = random.sample(range(X_train.shape[0]),self.batch_size)
                y_hat = np.dot(X_train[random_rows_index],self.coef_) + self.intercept_
                slope_of_intercept  = -2 * np.mean(y_train[random_rows_index] - y_hat)
                self.intercept_ = self.intercept_- (self.learning_rate * slope_of_intercept) 

                slope_of_coefficents  =  -2 * np.dot((y_train[random_rows_index] - y_hat),X_train[random_rows_index])/X_train.shape[0]
                self.coef_ = self.coef_ - (self.learning_rate * slope_of_coefficents )
        print('intercept :',self.intercept_)
        print('coefficents :',self.coef_)
        
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_



In [67]:
#mb_object = MiniBatchGradientDescantRegressor(batch_size=int(X_train.shape[0]/10))
mb_object = MiniBatchGradientDescantRegressor(batch_size=35)
mb_object.fit(X_train,y_train)

intercept : 130.0589226563507
coefficents : [1.15695683 1.02467457 1.41589486 1.33385217 1.14424578 1.099334
 0.7450008  1.26634055 1.42737305 1.25795451]


In [69]:
mb_object = MiniBatchGradientDescantRegressor(batch_size=35,learning_rate=0.01,epoches=50)
mb_object.fit(X_train,y_train)

intercept : 151.19386490968762
coefficents : [ 1.84618881  1.19217461  3.06718672  2.62980903  1.76998665  1.59452925
 -0.35384237  2.44064372  3.10496503  2.28167623]


In [70]:
y_pred = mb_object.predict(X_test)
print('r2_score',r2_score(y_test,y_pred))

r2_score -0.0010418279563417787


In [98]:
# now chaning the batch size learning rate epoaches 
# you improve model perform
mb_object = MiniBatchGradientDescantRegressor(batch_size=int(X_train.shape[0]/75),learning_rate=0.0001,epoches=1000)
mb_object.fit(X_train,y_train)

intercept : 150.0321611305994
coefficents : [1.16473236 1.0350249  1.43023938 1.336499   1.15526367 1.12200339
 0.7240043  1.29094964 1.42752007 1.26293022]


In [99]:
y_pred = mb_object.predict(X_test)
print('r2_score',r2_score(y_test,y_pred))

r2_score -0.009517042865060832


do not know why  my model perform is so bad
lakin sir ka acha aa raha tha

sir code solution 

In [100]:
import random

class MBGDRegressor:
    
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            
            for j in range(int(X_train.shape[0]/self.batch_size)):
                
                idx = random.sample(range(X_train.shape[0]),self.batch_size)
                
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                #print("Shape of y_hat",y_hat.shape)
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [102]:
mbr = MBGDRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=100)
mbr.fit(X_train,y_train)

154.42355433110717 [  26.5303632  -145.84946451  451.02766624  305.10979476  -23.46173487
  -89.75707423 -193.90184215  113.614995    408.37101798  111.15172016]


In [104]:
y_pred = mbr.predict(X_test)
print('r2_score :',r2_score(y_test,y_pred))

r2_score : 0.4537923171906789


# Using SGDRegressor
in sklearn 
we implement the mini batch gradient descant using sklearn 

In [105]:
from sklearn.linear_model import SGDRegressor

In [107]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.2)

In [108]:
batch_size = 35

for i in range(100):
    
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])

In [109]:
sgd.coef_

array([  12.20255645, -129.8940108 ,  479.74140431,  307.344511  ,
        -28.65068555, -105.09963665, -171.85621328,  105.0728412 ,
        397.15199789,  117.34549384])

In [111]:
sgd.intercept_

array([158.51288377])

In [112]:
y_pred = sgd.predict(X_test)
print('r2_score :',r2_score(y_test,y_pred))

r2_score : 0.44683741660201903
