In [21]:
import numpy as np

generator = np.random.default_rng(123)
ratings = np.round(generator.uniform(low=0.0, high=10.0, size=(10, 2)))
ratings[[1,2,7,9], [0,0,0,0]] = np.nan

print(ratings)


[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [ 5.  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [nan  5.]]


In [28]:
movie= ratings[:,0]
movie[[1,2,7,9]]= 0
# index = np.isnan(movie)
# np.argwhere(index)
movie

array([7., 0., 0., 9., 8., 5., 8., 0., 9., 0.])

In [29]:
director_rating = ratings[:,1]
director_rating

array([1., 2., 8., 3., 9., 2., 2., 6., 2., 5.])

In [37]:
x = (movie + director_rating)[:,np.newaxis]
x

array([[ 8.],
       [ 2.],
       [ 8.],
       [12.],
       [17.],
       [ 7.],
       [10.],
       [ 6.],
       [11.],
       [ 5.]])

In [38]:
np.concatenate((ratings,x), axis=1)

array([[ 7.,  1.,  8.],
       [ 0.,  2.,  2.],
       [ 0.,  8.,  8.],
       [ 9.,  3., 12.],
       [ 8.,  9., 17.],
       [ 5.,  2.,  7.],
       [ 8.,  2., 10.],
       [ 0.,  6.,  6.],
       [ 9.,  2., 11.],
       [ 0.,  5.,  5.]])

# Fish Promblem

In [51]:
import numpy as np

locs = np.array([
    [0,0,0],
    [1,1,2],
    [0,0,0],
    [2,1,3],
    [5,5,4],
    [5,0,0],
    [5,0,0],
    [0,0,0],
    [2,1,3],
    [1,3,1]
])

generator = np.random.default_rng(1010)
w = generator.normal(size=10)
weights = np.round(w, decimals=3)
weights[:,np.newaxis]
# [-1.699  0.538 -0.226 -1.09   0.554 -1.501  0.445  1.345 -1.124  0.212]


array([[-1.699],
       [ 0.538],
       [-0.226],
       [-1.09 ],
       [ 0.554],
       [-1.501],
       [ 0.445],
       [ 1.345],
       [-1.124],
       [ 0.212]])

In [78]:
unique = np.unique(
    locs,
    return_counts=True, 
    axis=0,
    #return_index=True
    )
unique

(array([[0, 0, 0],
        [1, 1, 2],
        [1, 3, 1],
        [2, 1, 3],
        [5, 0, 0],
        [5, 5, 4]]),
 array([0, 1, 9, 3, 5, 4], dtype=int64),
 array([3, 1, 1, 2, 2, 1], dtype=int64))

In [ ]:
np.array([0, 1, 9, 3, 5, 4])

In [81]:
np.argsort(locs)


array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [1, 0, 2],
       [2, 0, 1],
       [1, 2, 0],
       [1, 2, 0],
       [0, 1, 2],
       [1, 0, 2],
       [0, 2, 1]], dtype=int64)

# taco truck

In [82]:
import numpy as np

generator = np.random.default_rng(999)
schedules = generator.integers(low=0, high=5, size=(1000, 21))

print(schedules)

[[4 3 0 ... 2 0 0]
 [2 4 3 ... 3 3 2]
 [1 0 1 ... 1 2 1]
 ...
 [2 2 1 ... 3 1 4]
 [1 0 3 ... 2 3 2]
 [1 1 4 ... 2 4 2]]


In [ ]:
np.whereschedules