# promblem 1


In [60]:
import numpy as np
generator = np.random.default_rng(999)
love_score = np.round(generator.uniform(low=0,high= 100,size=10),2)
print(love_score)

[77.88 17.22 71.36 75.03 17.11 90.19 14.18 61.12 91.09 19.08]


In [61]:
person1 =np.round(generator.uniform(low=0,high= 100,size=10),2)
person2 =np.round(generator.uniform(low=0,high= 100,size=10),2)
person1.shape = (1,10) 
person2.shape=  (10,1)

In [62]:
print(np.abs(person1 -person2))

[[ 6.28 11.75  1.83 14.37  1.21 20.58 45.33 30.76 20.17 23.41]
 [39.87 45.34 35.42 47.96 32.38 13.01 11.74  2.83 13.42 57.  ]
 [12.46 17.93  8.01 20.55  4.97 14.4  39.15 24.58 13.99 29.59]
 [15.19 20.66 10.74 23.28  7.7  11.67 36.42 21.85 11.26 32.32]
 [11.36 16.83  6.91 19.45  3.87 15.5  40.25 25.68 15.09 28.49]
 [11.41  5.94 15.86  3.32 18.9  38.27 63.02 48.45 37.86  5.72]
 [25.89 31.36 21.44 33.98 18.4   0.97 25.72 11.15  0.56 43.02]
 [18.79 24.26 14.34 26.88 11.3   8.07 32.82 18.25  7.66 35.92]
 [ 0.81  4.66  5.26  7.28  8.3  27.67 52.42 37.85 27.26 16.32]
 [50.63 56.1  46.18 58.72 43.14 23.77  0.98 13.59 24.18 67.76]]


# promblem 2


In [84]:
import numpy as np

generator = np.random.default_rng(80085)
scores = np.round(generator.uniform(low=30, high=100, size=15))

print(scores)
# [68. 36. 76. 57. 56. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


[68. 36. 76. 57. 56. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


In [93]:
mask = scores[scores <60]

#print(scores)
mask

[ True  True  True]


array([0., 0., 0., 0., 0., 0.])

In [77]:
scores = scores[scores <60]
scores = np.sort(scores)
scores[:3]= 0
print(scores)

[ 0.  0.  0. 54. 56. 57.]


In [78]:
print(scores)

[ 0.  0.  0. 54. 56. 57.]


# Promblem 3


In [94]:
field = np.zeros(shape=(10,10))
print(field)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
np.random.Generator.normal(
    low = 1,
    high = 21,
    size=(10,10),
    replace = False
    )

In [103]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.default_rng().normal(mu, sigma, 10)
print(s)

[-0.09337067 -0.03134041 -0.14813758  0.04542998 -0.07459421  0.05824213
 -0.00570736  0.03238419 -0.07922284 -0.08953621]


In [ ]:
value = np.random.default_rng().normal(field,20)
#r =
#field[value]
value

In [ ]:
int_value = np.rint(value).astype(int)
field[int_value]
#do again this