##  Broadcasting

### what is broadcasting 

#### 1 dim 

In [1]:
# probaly you see it but don't realise
# example when add a vector(1d array) to a scaler
import numpy as np
np.array([1,2,3]) + 0.5 
# in the essence numpy is expanding the sclaer than add it
# like this
# [1,2,3] + [0.5,0.5,0.5]
# element wise additon between the arrays
# under the hood numpy does not actually do it is horrible in efficient
# but in the essence what's happeing 
# 1 + 0.5 = 1.5
# 2 + 0.5 = 2.5
# 3 + 0.5 = 3.5
np.array([1,2,3]) + np.array([0.5,0.5,0.5])

array([1.5, 2.5, 3.5])

#### 2 dim 

In [6]:
foo = np.array([
    [1,1,1],
    [2,2,2],
])

boo = np.array(
    [1,0,-1]
)
# broadbcasting  (2d array ) 
# matrix and a vector  it convert vector to matrix 
#  before      -->      after 
# (2,3) + (1,3) --> (2,3) + (2,3)
# match the shape and do element wise operation
# in essence it do like this 
[1,1,1] + [1,0,-1]
[2,2,2] + [1,0,-1]
foo + boo 

array([[2, 1, 0],
       [3, 2, 1]])

In [7]:
# what happen if foo have two element
foo = np.array([
    [1,1,1],
    [2,2,2],
])
boo = np.array([1,0])
foo + boo

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

### how can broadcasting work and when we use it 

#### broadcasting rules 
suppose we want to add two array A and B ...
1. Moving backwards from the last dimension of each array,
2. We check if their dimensions are "compatible". Dimensions are compatible if they are equal or either of them is 1
3. If all of A's dimensions are compatible with B's dimensions, or vice versa, they are compatible arrays

1. (m,n) +(1,n) = (m,n)
2. (1,n) +(m,n) = (m,n)
3. (1,n) +(1,m) = (m,n)

#### 1st example 

In [15]:
np.random.seed(1234)
A = np.random.randint(low =1 ,high= 10, size=(3,4))
B = np.random.randint(low =1 ,high= 10, size=(3,1))

#                           A           B
# A : (3,4)            [[4 7 6 5]      [[7]
# B : (3,1)             [9 2 8 7]  +    [3]
#                       [9 1 6 1]]      [1]]

# numpy  compare it's last dimesnion A : 4 and B : 1 then it convert B 4
# now last 2nd element is 3 so they are compatiable 
# now left is whatever procedure we wanted to do  
#                           A           B
# A : (3,4)            [[4 7 6 5]      [[7,7, 7, 7]
# B : (3,4)             [9 2 8 7]  +    [3,3, 3, 3]
#                       [9 1 6 1]]      [1,1, 1, 1]]
print( A +B)

[[11 14 13 12]
 [12  5 11 10]
 [10  2  7  2]]


In [ ]:
print(A)
print(B)

#### 2nd example 

In [18]:
np.random.seed(4321)
A = np.random.randint(low =1 ,high= 10, size=(4,4))
B = np.random.randint(low =1 ,high= 10, size=(2,1))

#                           A            B
# A : (4,4)            [[3 9 3 2]       [[7]
# B : (2,1)             [8 6 3 5]   +    [2]
#                       [7 1 9 7]
#                       [6 4 2 2]]
# compare last element A: 4 and B:1 so numpy expalnd this A:4, B:4
# now their is no way to expalnd  A:4, B:2 to 2 to 4 numpy raise  ValueError 
print(A +B)


ValueError: operands could not be broadcast together with shapes (4,4) (2,1) 

#### 3rd example 

In [26]:
np.random.seed(1111)
A = np.random.randint(low =1 ,high= 10, size=(3,1,4))
B = np.random.randint(low =1 ,high= 10, size=(2,1))

# default 
#                   A                                               B
# A: (3,1,2)   [[[8 6 2 3]  [[5 9 7 5]] [[9 7 3 7]]  ]         [ [9] 
# B: (  2,1)                                                     [4] ]
#   
# last element 
# now we expand the last element we expand the B element to 4
#                   A                                               B
# A: (3,1,2)   [[[8 6 2 3]  [[5 9 7 5]] [[9 7 3 7]]  ]         [ [9,9, 9, 9] 
# B: (  2,2)                                                     [4,4, 4, 4] ]
# 
#  last 2nd element    
# now we expand the last compare the last 2nd element and expand A to 2     
#                   A                                               B
# A: (3,2,2)   [[[8 6 2 3]  [[5 9 7 5]] [[9 7 3 7]]  ]         [ [9,9, 9, 9] 
# B: (  2,2)    [[8 6 2 3]  [[5 9 7 5]] [[9 7 3 7]]              [4,4, 4, 4]   ]   
#     
#  last 3rd element         
# now we compare the last 3 element and make A: 3 ,B; nothing so B--> 3   
#                   A                                               B
# A: (3,2,2)    [[8 6 2 3]  [[5 9 7 5]] [[9 7 3 7]]            [ [9,9, 9, 9] [9,9, 9, 9]  [9,9, 9, 9]
# B: (3,2,2)    [[8 6 2 3]  [[5 9 7 5]] [[9 7 3 7]]              [4,4, 4, 4] [4,4, 4, 4]  [4,4, 4, 4]  ]   
print( A + B)
# to complete our mental model how math work in different array 
# before I close out this lecture I want to say that
# broadcasting  expansion process in my mind I don't actually go through
# this formal process thinking of shapes of tuple 
# I just visualized the shape of array and how they expand into identical sizes


[[[17 15 11 12]
  [12 10  6  7]]

 [[14 18 16 14]
  [ 9 13 11  9]]

 [[18 16 12 16]
  [13 11  7 11]]]

In [1]:
import numpy as np
arr1 = np.arange(0,5).reshape(1,5)
arr2 = np.arange(0,5).reshape(5,1)
print(arr1 + arr2)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [1]:
import numpy as np
arr1 = np.arange(0,9).reshape(3,3)
arr2 = np.arange(10,13).reshape(1,3)
print(arr1 + arr2)

[[10 12 14]
 [13 15 17]
 [16 18 20]]


In [3]:
# tip if don't know reshape use (,-1) in last

In [4]:
np.random.seed(1111)
A = np.random.randint(low = 1, high = 10, size = (3, 1, 4))
B = np.random.randint(low = 1, high = 10, size = (2, 1))

print(A)
print(B)



[[[8 6 2 3]]

 [[5 9 7 5]]

 [[9 7 3 7]]]
[[9]
 [4]]


In [5]:
print(A+B)

[[[17 15 11 12]
  [12 10  6  7]]

 [[14 18 16 14]
  [ 9 13 11  9]]

 [[18 16 12 16]
  [13 11  7 11]]]


In [3]:
import numpy as np
a = np.array([1, 2, 3])
b = 2
result = a * b  # Broadcasting b to match the shape of a
result

array([2, 4, 6])

# New axis
how to use New axis keyborad to increase the dimesnality of an array 
and why it is useful 

### before

In [28]:
C = np.array([3,11,4,5])
D = np.array([5,8,3])
# your goal is to built a 4 by 3 matrix 
# where Cij = Aij -  Bij
# in other words your goal is to subtract every element of C to every element of D
# if you do C- D you get ValueError because array's size are not compatiable 
print(C - D)


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

### After

In [31]:
print(C[:,np.newaxis])
print('-------')
print(D[np.newaxis,:])

[[ 3]
 [11]
 [ 4]
 [ 5]]
-------
[[5 8 3]]


In [38]:
#   C             D
# [[ 3]         [[5 8 3]]
#  [11]   - 
#  [ 4]
#  [ 5]]

# if this numpy do broadcasting
#   C             D
# [[ 3, 3, 3]         [[5 8 3]
#  [11,11, 11]   -     [5 8 3]
#  [ 4, 4, 4]          [5 8 3]
#  [ 5,5, 5]]         [5 8 3]]

(4, 1)
(1, 3)


In [39]:
C[:,np.newaxis] - D[np.newaxis,:]

array([[-2, -5,  0],
       [ 6,  3,  8],
       [-1, -4,  1],
       [ 0, -3,  2]])

In [42]:
print(C[:,np.newaxis].shape)
print(D[np.newaxis,:].shape)

(4, 1)
(1, 3)


In [ ]:
print(C.shape)
print(D.shape)

(4,)
(3,)


# tanspose

In [ ]:
tra= np.array([
    [12,13],
    [14,15]
    ])
tra.transpose()
#change rows to columns or you say vice versa

array([[12, 14],
       [13, 15]])

# Reshape
How to change the shape of an array 

In [46]:
# directly by np
foo = np.arange(1,9)
np.reshape(foo, shape=(2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### C style 
aka row major style 

In [48]:
# reshape by method
# see in animation 49.22
# first axis order first 
print(foo.reshape((4,2) ,order='C'))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### forton style 
aka column major order 

In [49]:
# last axis order first 
print(foo.reshape((4,2) ,order='F'))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [50]:
# c style
print(foo.reshape((2,2,2), order='C'))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [51]:
# forton style 
print(foo.reshape((2,2,2), order='F'))

[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]


### trick of -1

In [55]:
# when you reshape an array you use -1 
# to exactly one of the new shape dimension and numpy will calculate it 
# if you do foo.reshape(first dimensio is 4 i don't think of next dimension just pass -1 )
# numpy will calucate it ooh it need 4 by 2 array 
foo.reshape(4,-1)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### note

In [60]:
# all this array we are creating a copy of array 
# actually we type
print(foo) # it does not modify it 
# it actually create a new array with new data 

[1 2 3 4 5 6 7 8]


if you pass in parameter of function.       
then it will not change it globally(for instance).      
changes is not permanent.       

In [ ]:
print(foo)

[1 2 3 4 5 6 7 8]


In [ ]:
foo = foo.reshape(2,2,2)
# it actually create un-neccssary  copy of it
# so a better way is 

if you  assign it variable then changes are peramantely in program      
do wisely             
assign when you  want to change it permentally           

In [ ]:

foo.shape = (2,2,2)
print(foo)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Boolean indexing
one of powerful feature in numpy is boolean indexing 
With boolean indexing, you can subset an array A using another array B of boolean values.

In [62]:
import numpy as np
foo = np.array([
    [3, 9, 7],
    [2, 0, 3],
    [3, 3, 1]
])
foo

array([[3, 9, 7],
       [2, 0, 3],
       [3, 3, 1]])

#### we want to replace every 3 wih zero 

In [63]:
#foo ==3
#both are same to do subset
mask = foo ==3
print(mask)
# true means on that index position is 3 
# false means on that index position 3 is not persent 

[[ True False False]
 [False False  True]
 [ True  True False]]


In [ ]:
#foo[foo ==3]
print(foo[mask])

[3 3 3 3]


In [ ]:
# now setting thus variable to 0 
foo[mask] = 0
print(foo)

[[0 9 7]
 [2 0 0]
 [0 0 1]]


### pick specific elements 

In [65]:
rows_1_and_3 = np.array([True,False,True]) # like foo([0,2])
columns_1_and_2 =  np.array([False,True,True]) # like foo(:,[1,2])


In [ ]:
foo[rows_1_and_3,:] #like foo[[0,2],:] object[[row_index,col_index]]

array([[0, 9, 7],
       [0, 0, 1]])

In [ ]:
foo[:,columns_1_and_2 ] #like foo[:,[1,2]]

array([[9, 7],
       [0, 0],
       [0, 1]])

### how numpy treat boolean indexing 

In [67]:
# you will be suprised by the result one -d array
# actually numpy treat boolean indices like integers .
# where the integer used are the true indices of element 
# numpy treat index 
# rows_1_and_3= [true,false, true] just like he treat index [0,2]
# columns_1_and_2= [false,true,true] just like he teate index [1,2]
foo[rows_1_and_3,columns_1_and_2] #foo([0,2],[1,2])
# select element
#(0,1) and (2,2)

array([9, 1])

# Logical operators

In [ ]:
b1 = np.array([False, False, True, True])
b2 = np.array([False, True, False, True])

b1 & b2  # [False, False, False,  True], and, intersection
b1 | b2  # [False,  True,  True,  True], or, union
b1 ^ b2  # [False,  True,  True, False], xor
~np.array([False, True]) # array([ True, False]) inverse


## Example case study 

In [ ]:
names = np.array(["dennis",'dee','charlie','mac','frank'])
ages = np.array([43,44,43,42,74])
gender = np.array(['male','female','male','male','male'])

### who' at least 44

In [ ]:
#ques who' at least 44
ages >= 44 #greather than or equal to 

array([False,  True, False, False,  True])

In [ ]:
names[ages >= 44]# who's name of the person
# numpy do correspong element

array(['dee', 'frank'], dtype='<U7')

### Which males are over 42 ?

In [ ]:
# Which males are over 42 ?
#tip use parenthesis to sepecify condition
(ages > 42)  & (gender == 'male')


array([ True, False,  True, False,  True])

In [ ]:
names[(ages > 42)  & (gender == 'male')]

array(['dennis', 'charlie', 'frank'], dtype='<U7')

### who's not a male or is younger than 43

In [ ]:
#and who's not a male or is younger than 43
~(gender=='male') | (ages > 43 )

array([False,  True, False, False,  True])

In [ ]:
names[~(gender=='male') | (ages > 43 )]

array(['dee', 'frank'], dtype='<U7')

# Nan
You can use NaN to represent `missing or invalid values`. NaN is a floating point constant that numpy reserves and treats specially.

In [72]:
bot = np.ones(shape=(3,4))
bot[[0,2],[1,2]] = np.nan
print(bot)
print(np.isnan(bot))

[[ 1. nan  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1. nan  1.]]
[[False  True False False]
 [False False False False]
 [False False  True False]]


In [ ]:
# numpy design nan so nan 

### Ask question is there a null value 

In [ ]:
# if you want to find which element of bot are nan value
# you do 
bot==np.nan
# you will be suprise that it will return false 
#observe all are false 
#logic what is empty ==empty
#operation are not defined
# sometimes this cause silent bugs
# because equivalence between missing and not-valid value 
# is not defined
# In pratice this behaviour prevents silent bugs and creeping your program

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
#all true
#nothing same beahaviour
# empty means empty 
bot != np.nan

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### operation between nan 

In [70]:

np.nan == np.nan

False

In [71]:
np.nan != np.nan

True

### np.isnan

In [ ]:
# to find the nan or missing value in numpy you use numpy isnan function
print(np.isnan(bot))

[[False  True False False]
 [False False False False]
 [False False  True False]]


### note important 

NaN is a special floating point constant, so it can only exist inside an array of floats. If you try inserting NaN into an array of integers, booleans, or strings, you’ll get an error or unexpected behavior.

In [76]:
import numpy as np 
int_array = np.array([1,2,3],dtype=np.int64)
# assign it to nan values
int_array[1] = np.nan
print(int_array)

ValueError: cannot convert float NaN to integer

# Infinity
how can you reprsent infinite values in numpy 
postive and negative


numpy reserve floating point constant for postive and negative infinity that behave specily 

In [81]:
# you can put on the array 
np.array([np.inf,-np.inf])

array([ inf, -inf])

### occured when you divide by 0

In [82]:
# this occured when you divide by 0 
np.array([1,-1])/0

C:\Users\sumit\AppData\Local\Temp\ipykernel_7720\2458694660.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([1,-1])/0


array([ inf, -inf])

### operation with infintiy 

In [83]:
# infinity +,-,*,/ with some constant --> infinity 
np.inf + 5

inf

In [84]:
np.inf + np.inf

inf

In [85]:
# one infinity - another infinity  have undefined behaviour 
np.inf - np.inf

nan

In [86]:
# infinity divide by infinity 
np.inf / np.inf

nan

#### equilavnece in infinity 

In [87]:
# positive infity equalts to postivie infinity 
np.inf == np.inf

True

In [88]:
# negative infinity equalt to negative infity 
-np.inf == -np.inf

True

### find inf in a array 

In [93]:
one_dim_array = np.array([1,2,np.inf,3.1, -np.inf , 2.5])
one_dim_array

array([ 1. ,  2. ,  inf,  3.1, -inf,  2.5])

In [94]:
one_dim_array == np.inf

array([False, False,  True, False, False, False])

In [96]:
one_dim_array == -np.inf

array([False, False, False, False,  True, False])

In [97]:
#you can also use numpy function
np.isinf(one_dim_array)

array([False, False,  True, False,  True, False])

In [98]:
np.isneginf(one_dim_array)

array([False, False, False, False,  True, False])

# Random Generator
How to use numpy random module
-  to shuffle value arrays 
- sample value from array
- and draw values from host of a probablity distribution 
- and then everything I show you depricated and how to update it to modern standards

lets see an example rolling a six sided die three times in other words
draw three integers from the range of (0 to 6) with replacement 

### randit
choose number from given range and define array size 
shape of the array you want 

In [99]:
import numpy as np
np.random.randint(low=1,high=7,size=3)
# you get a different result . if you run on your machine 

array([3, 5, 5], dtype=int32)

### seed 
get  reproductaible result use seed

In [103]:
# if you want reproductaible result use seed
import numpy as np
np.random.seed(123)
np.random.randint(low=1,high=7,size=3)

array([6, 3, 5], dtype=int32)

In [13]:
np.random.seed(2357)
np.random.choice(
    a = np.array([1,2,3,4,5,6]),
    size= 3,
    replace= False,
    p = None
)

array([6, 5, 1])

### choice 
what happen if you want to draw values form 0 to 6 without replacement

#### equal probality 

In [137]:
#we make the probabilty bias
np.random.seed()
np.random.choice(
    a = np.array([1,2,3,4,5,6]), # our array 
    size= 3, # size of our array we choice 
    replace= False, # if we use if you not replace 
    p =None          # probabilties 
)

array([1, 5, 6])

#### un-equal probality 

In [ ]:
#we make the probabilty bias
np.random.seed()
np.random.choice(
    a = np.array([1,2,3,4,5,6]), # our array 
    size= 3, # size of our array we choice 
    replace= False, # if we use if you not replace 
    p =np.array([0.1,0.1,0.1,0.1,0.3,0.3]) # probabilties 
)
# your probalities array element 
# equal to your array element 

In [150]:
np.random.choice(
    a = np.array(['you','can','use','stings']),
    size = 2,
    replace = False,
    p = None
)

array(['can', 'use'], dtype='<U6')

In [ ]:
# what is thr probablity that you take from the Sanskrit sentences 
# and it is a sentence 

### sample rows from a 5*2 matrix 

In [1]:
import numpy as np
foo = np.array([
    [1,2], # 0
    [3,4], # 1
    [5,6], # 2
    [7,8], # 3 
    [9,10],# 4
])
print(foo)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [77]:
# you can use randint and choice for that 
# the trick is to generate a random 1d array of row indices
# and use that result to select rows from the array you want to sample
# example randint
# three rows from foo with replacement 
np.random.seed(1234)
rand_rows = np.random.randint(
    low = 0,
    high = foo.shape[0],
    size = 3 # we want sample 3 values 
    
)

print(rand_rows)

[3 4 4]


In [3]:
foo[rand_rows]
# an array of random rows selected from foo 
# this is with replacement if you want to do without replacement 
# use choice function 

array([[ 7,  8],
       [ 9, 10],
       [ 9, 10]])

In [78]:
np.random.seed(1234)
rand_rows = np.random.choice(
    a = np.arange(start=0,stop=foo.shape[0]),# number of rows in foo.shape
    replace=False,
    size= 3
)
print(rand_rows)
# we get the random row indices get back

[4 0 1]


In [79]:
foo[rand_rows]

array([[ 9, 10],
       [ 1,  2],
       [ 3,  4]])

## permuation
we can also the shuffle the array 

In [88]:
np.random.permutation(foo)

array([[ 9, 10],
       [ 5,  6],
       [ 3,  4],
       [ 1,  2],
       [ 7,  8]])

## sample from probality distribution

### uniform

In [90]:
np.random.uniform(low=1.0,high=2.0,size=(2,2))

array([[1.53814784, 1.7906221 ],
       [1.46583634, 1.43533225]])

### normal

In [92]:
np.random.normal(loc=2.3,scale=5.7,size=(3,3))

array([[ 8.0846412 , -0.87503987, -0.12025437],
       [ 3.08372658,  1.8980756 ,  4.15474764],
       [-0.39907284, -6.87254036,  5.33677489]])

### many more ....

In [ ]:
np.random
# click on clrl to see all probabilty distribution

## all knowlegde is depricated 

In [93]:
# lets suppose we are using 
# numpy Version 1.1
# we get input to a 
np.random.seed(123)
np.random.randint(3,size = 3)
# lets example generator is
#ABC1 a random number generator 
# under the hood ABC get you a statistically vaild sequence of random number 
[0,2,2]
# anyone using numpy writes the same exact code and gets back the same exact sequence then 
# then somebody comes a discovers a new random generator 
#DEF2 it creates a better job of creating statiscally valid number so numpy decides to replace ABC1 to DEF2
# numpy version 1.2  ---> DEF2  
# so when you upgrate to numpy version 1.2
# and run the same exact code 

array([2, 1, 2])

In [ ]:
# numpy version 1.2
np.random.seed(123)
np.random.randint(3,size = 3)
# in generator DEF2
# you get a different sequence of random number
# this is an issue because one some people have code or documentation that might
# if random number they are generating suddenly change and two if people cannot share a two reprocuibale example 
# because they are on at different version of numpy that is really incovient 
# I mean think of all old examples stack overflow that would instanly become non-reproducible
# because numpy updated their random number generator    

In [ ]:
# and someone come along and built a 
# new random number generator GHI 3 faster but less vaild
# it is way faster than DEF2 and less statistally valid
# now numpy have problem whether to use faster generator or the more accurate generator
np.random.Generator()
# now solution is numpy Generator class lets pick you which random number genernator 
# you want to pick 
# for the sake of simplicity I am using numpy default random number genratro 

# create a generator

In [4]:
import numpy as np
generator = np.random.default_rng(123)
generator

'Generator(PCG64)'

#### sample 3 elements betweewn 1 to 6 with replacementt

In [5]:
# old method 
np.random.randint(low= 0 ,high=7,size=(3))

array([4, 1, 5])

In [6]:
#new method
generator.integers(low=0,high=7,size=3)

array([6, 6, 6], dtype=int64)

#### sample 3 elements betweewn 1 to 9 without replacementt

In [8]:
np.random.choice(a=10,size=3,replace=True)

array([0, 1, 7])

In [9]:
generator.choice(a=10,size=3,replace=True)

array([3, 1, 9], dtype=int64)

#### random permutations

In [ ]:
np.random.permutation(foo)

In [ ]:
generator.permutation(foo,axis=0)

#### all the probablity distribution 

In [ ]:
np.random.uniform(low=0,high=10,size=(3,3))

In [10]:
generator.uniform(low=0,high=10,size=(3,3))

array([[2.61692424, 3.19097058, 1.18091233],
       [2.41766293, 3.18533929, 9.64079245],
       [2.63649804, 4.41006122, 6.09870809]])

In [ ]:
# uniform ,normal,binomaial .....