# Where
it is a vectazoried approach  to solve if else conditon

In [74]:
#make a random generator
import numpy as np
generator = np.random.default_rng(12)

In [75]:
#sample 1M intergers form 0 to 5
bar = generator.integers(low=1,high=6,size=2*10**6)
print(bar)

[4 2 5 ... 2 3 3]


In [76]:
#sample 1M intergers form 0 to 5
foo = generator.integers(low=1,high=6,size=2*10**6)
print(foo)

[3 5 2 ... 4 1 5]


In [77]:
# if even double the num odd half the number


In [78]:
#np.where(condition[x,y])
baz = np.where(bar%2==0,foo*2,foo/2)
baz

array([ 6. , 10. ,  1. , ...,  8. ,  0.5,  2.5])

In [79]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
#if arr is even cat odd is dog
cond= np.where(arr%2==0,'cat','dog')
cond

array([['dog', 'cat', 'dog'],
       ['cat', 'dog', 'cat'],
       ['dog', 'cat', 'dog']], dtype='<U3')

In [81]:
#animal = np.array(['cat','dog'])


# Math functions
if you learn how to use one you nearly learn all 0f them

In [82]:
squeze = np.array([ 
    [5. , 2., 9.],
    [1.,  0., 2.],
    [1. , 7., 8.]
])
squeze

array([[5., 2., 9.],
       [1., 0., 2.],
       [1., 7., 8.]])

In [83]:
np.sum(squeze)

35.0

Axis = 0 colums wise

In [84]:
np.sum(squeze,axis=0) # sum coulmn wise

array([ 7.,  9., 19.])

Axis 1 rows wise 

In [85]:
np.sum(squeze,axis=1)#  sum rows wise

array([16.,  3., 16.])

if nan value persent

In [86]:
squeze[0,1]= np.nan
squeze

array([[ 5., nan,  9.],
       [ 1.,  0.,  2.],
       [ 1.,  7.,  8.]])

In [87]:
np.sum(squeze)
#because numpy except all values to be non-nan
#sol use where func remove  nan

nan

1st method

In [88]:
np.sum(squeze,where =~np.isnan(squeze))
#we use  negation(~)

33.0

2nd method

In [89]:
np.sum(np.nan_to_num(squeze))

33.0

3rd method      

In [90]:
np.nansum(squeze)
#it remove (skip)the nan then sum it
#

33.0

In [91]:
num =np.array([1., 2. ,3., 4. ,5.])
np.mean(num)
num[[3]]= np.nan
print(num)

[ 1.  2.  3. nan  5.]


In [92]:
np.nanmean(num)

2.75

# Truth value Testing

## all


In [93]:
foo = np.array([
    [np.nan,    4.4],
    [   1.0,    3.2],
    [np.nan, np.nan],
    [   0.1, np.nan]
])


In [94]:
np.isnan(foo) #

array([[ True, False],
       [False, False],
       [ True,  True],
       [False,  True]])

In [95]:
np.all(np.isnan(foo),axis=1) # check all rows

array([False, False,  True, False])

In [96]:
np.all(np.isnan(foo),axis=0) # check all columns

array([False, False])

## Any
You can use the any() function to check if any of the values in an array meet some condition.

In [97]:
np.any(np.isnan(foo))

True

In [98]:
np.any(np.isnan(foo), axis=1)

array([ True, False,  True,  True])

In [99]:
np.any(np.isnan(foo), axis=0)

array([ True,  True])

# Concenatate

In [116]:
roux = np.zeros(shape=(3,2))
roux

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [114]:
gumbo = np.ones(shape=(3,2))
gumbo

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [119]:
np.concatenate((roux,gumbo),axis=0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [120]:
np.concatenate((roux,gumbo),axis=1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

# Staking

Vstack

for each array in the sequence:
    if the array is 1-d:
      promote the array to 2-d by giving it a new front axis
    if every array has the same shape:
      concatenate the arrays along axis 0
    else:
      throw an error


In [ ]:
#axis 0 add next column
[]
[]
[]

In [133]:
foo = np.array(['a', 'b'])
bar = np.array(['c', 'd'])
baz = np.array([['e', 'f']])
bingo = np.array([['g', 'h', 'i']])
#note we bracket to bind one unit

In [134]:
np.vstack((foo,bar))

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

hstack

if every array in the sequence is 1-d:
  concatenate the arrays along axis 0
else:
  if every array has the same shape excluding axis 1:
    concatenate arrays along axis 1
  else:
    throw an error


In [ ]:
#axis 1  add next row
[] ,[] ,[], []

In [135]:
np.hstack((foo,bar))

array(['a', 'b', 'c', 'd'], dtype='<U1')

Stack

a sequence of arrays to combine
axis which tells stack() to create a new axis along which to combine the arrays.

In [138]:
np.stack((foo,bar),axis=0)

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

# Sorting
You can use numpy’s sort() function to sort the elements of an array.

sort() takes three primary parameters:

1. a: the array you want to sort
2. axis: the axis along which to sort. (The default, -1, sorts along the last axis.)
3. kind: the kind of sort you want numpy to implement. By default, numpy implements quicksort.

In [142]:
foo = np.array([1, 7, 3, 9, 0, 9, 1])
np.sort(foo)
#actullay it create a copy of it 

array([0, 1, 1, 3, 7, 9, 9])

In [143]:
print(foo)

[1 7 3 9 0 9 1]


In [145]:
#if you want to create permanent do
#object.func()
foo.sort()
foo

array([0, 1, 1, 3, 7, 9, 9])

In [149]:
bone = np.array([10.,3.,np.nan,6.])
bone.sort()
bone

array([ 3.,  6., 10., nan])

In [151]:
#reverse if you want
np.sort(bone)[::-1]

array([nan, 10.,  6.,  3.])

In [155]:
-(np.sort(-bone))

array([10.,  6.,  3., nan])

## Multidimensional sorting

In [157]:
boo = np.array([
    [55, 10, 12],
    [20, 0, 33],
    [55, 92, 3]
])


along colums

In [158]:
np.sort(boo, axis=0)

array([[20,  0,  3],
       [55, 10, 12],
       [55, 92, 33]])

along rows

In [159]:
np.sort(boo, axis=1)

array([[10, 12, 55],
       [ 0, 20, 33],
       [ 3, 55, 92]])

along the last axes

In [160]:
np.sort(boo, axis=-1)

array([[10, 12, 55],
       [ 0, 20, 33],
       [ 3, 55, 92]])

argsort

In [161]:
foo = np.array([3, 0, 10, 5])
np.argsort(foo)

array([1, 0, 3, 2], dtype=int64)

unique

In [165]:
gar =np.array(['b', 'b', 'a', 'a', 'c', 'c'])
np.unique(gar)
#notice that it sorts and unique

array(['a', 'b', 'c'], dtype='<U1')

In [166]:
gar =np.array(['b', 'b', 'a', 'a', 'c', 'c'])
np.unique(gar,return_counts=True)

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 2], dtype=int64))

# Multidimension indexing